--Updates VEHICLE_TYPE_CODE_1

--Drop Existing TempTable if one exists
IF OBJECT_ID('tempdb.dbo.##TempTable') IS NOT NULL
DROP TABLE ##TempTable

--Create TempTable from CollisionID and the Vehicle Type Codes that we want to change
SELECT * INTO ##TempTable
FROM (
SELECT [NYC_Collisions].dbo.[Motor_Vehicle_Collisions_-_Crashes].COLLISION_ID, [NYC_Collisions].dbo.[Motor_Vehicle_Collisions_-_Crashes].VEHICLE_TYPE_CODE_1
FROM [NYC_Collisions].dbo.[Motor_Vehicle_Collisions_-_Crashes]
WHERE
[VEHICLE_TYPE_CODE_1] = 'Station Wagon/Sport Utility Vehicle' OR
[VEHICLE_TYPE_CODE_1] = 'PASSENGER VEHICLE' OR
[VEHICLE_TYPE_CODE_1] = 'SPORT UTILITY / STATION WAGON' OR
[VEHICLE_TYPE_CODE_1] = 'Pick-up Truck' OR
[VEHICLE_TYPE_CODE_1] = '4 dr sedan' OR
[VEHICLE_TYPE_CODE_1] = 'OTHER' OR
[VEHICLE_TYPE_CODE_1] = 'UNKNOWN' OR
[VEHICLE_TYPE_CODE_1] = 'Bike' OR
[VEHICLE_TYPE_CODE_1] = 'LARGE COM VEH(6 OR MORE TIRES)' OR
[VEHICLE_TYPE_CODE_1] = 'SMALL COM VEH(4 TIRES) ' OR
[VEHICLE_TYPE_CODE_1] = 'Tractor Truck Diesel' OR
[VEHICLE_TYPE_CODE_1] = 'LIVERY VEHICLE' OR
[VEHICLE_TYPE_CODE_1] = 'Dump' OR
[VEHICLE_TYPE_CODE_1] = 'E-Bike' OR
[VEHICLE_TYPE_CODE_1] = '2 dr sedan' OR
[VEHICLE_TYPE_CODE_1] = 'PK' OR
[VEHICLE_TYPE_CODE_1] = 'Flat Bed' OR
[VEHICLE_TYPE_CODE_1] = 'E-Scooter' OR
[VEHICLE_TYPE_CODE_1] = 'Moped' OR
[VEHICLE_TYPE_CODE_1] = 'Garbage or Refuse' OR
[VEHICLE_TYPE_CODE_1] = 'Carry All' OR
[VEHICLE_TYPE_CODE_1] = 'Tractor Truck Gasoline' OR
[VEHICLE_TYPE_CODE_1] = 'Tow Truck / Wrecker' OR
[VEHICLE_TYPE_CODE_1] = 'FIRE TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'Chassis Cab' OR
[VEHICLE_TYPE_CODE_1] = 'Tanker' OR
[VEHICLE_TYPE_CODE_1] = 'Motorscooter' OR
[VEHICLE_TYPE_CODE_1] = 'BICYCLE' OR
[VEHICLE_TYPE_CODE_1] = 'Ambul' OR
[VEHICLE_TYPE_CODE_1] = 'Motorbike' OR
[VEHICLE_TYPE_CODE_1] = 'Concrete Mixer' OR
[VEHICLE_TYPE_CODE_1] = 'Refrigerated Van' OR
[VEHICLE_TYPE_CODE_1] = 'Flat Rack' OR
[VEHICLE_TYPE_CODE_1] = '3-Door' OR
[VEHICLE_TYPE_CODE_1] = 'scooter' OR
[VEHICLE_TYPE_CODE_1] = 'LIMO' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'Beverage Truck' OR
[VEHICLE_TYPE_CODE_1] = 'TRAIL' OR
[VEHICLE_TYPE_CODE_1] = 'SCHOOL BUS' OR
[VEHICLE_TYPE_CODE_1] = 'FIRE' OR
[VEHICLE_TYPE_CODE_1] = 'Lift Boom' OR
[VEHICLE_TYPE_CODE_1] = 'Stake or Rack' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY' OR
[VEHICLE_TYPE_CODE_1] = 'subn' OR
[VEHICLE_TYPE_CODE_1] = 'Trailer' OR
[VEHICLE_TYPE_CODE_1] = 'Multi-Wheeled Vehicle' OR
[VEHICLE_TYPE_CODE_1] = 'TRACT' OR
[VEHICLE_TYPE_CODE_1] = 'Snow Plow' OR
[VEHICLE_TYPE_CODE_1] = 'E-Sco' OR
[VEHICLE_TYPE_CODE_1] = 'AMBU' OR
[VEHICLE_TYPE_CODE_1] = 'E-Bik' OR
[VEHICLE_TYPE_CODE_1] = 'Pedicab' OR
[VEHICLE_TYPE_CODE_1] = 'TOW TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'UNKNO' OR
[VEHICLE_TYPE_CODE_1] = 'SCHOO' OR
[VEHICLE_TYPE_CODE_1] = 'COM' OR
[VEHICLE_TYPE_CODE_1] = 'Open Body' OR
[VEHICLE_TYPE_CODE_1] = 'DELIV' OR
[VEHICLE_TYPE_CODE_1] = 'COMME' OR
[VEHICLE_TYPE_CODE_1] = 'Tow t' OR
[VEHICLE_TYPE_CODE_1] = 'Bulk Agriculture' OR
[VEHICLE_TYPE_CODE_1] = 'UNK' OR
[VEHICLE_TYPE_CODE_1] = 'Firetruck' OR
[VEHICLE_TYPE_CODE_1] = 'BOX T' OR
[VEHICLE_TYPE_CODE_1] = 'UTILI' OR
[VEHICLE_TYPE_CODE_1] = 'SCOOT' OR
[VEHICLE_TYPE_CODE_1] = 'DELV' OR
[VEHICLE_TYPE_CODE_1] = 'FIRET' OR
[VEHICLE_TYPE_CODE_1] = 'Pickup with mounted Camper' OR
[VEHICLE_TYPE_CODE_1] = 'COMMERCIAL' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY Ambul' OR
[VEHICLE_TYPE_CODE_1] = 'AMB' OR
[VEHICLE_TYPE_CODE_1] = 'FORKL' OR
[VEHICLE_TYPE_CODE_1] = 'Pallet' OR
[VEHICLE_TYPE_CODE_1] = 'ELECT' OR
[VEHICLE_TYPE_CODE_1] = 'pas' OR
[VEHICLE_TYPE_CODE_1] = 'UTIL' OR
[VEHICLE_TYPE_CODE_1] = 'Lunch Wagon' OR
[VEHICLE_TYPE_CODE_1] = 'PICK UP' OR
[VEHICLE_TYPE_CODE_1] = 'pick' OR
[VEHICLE_TYPE_CODE_1] = 'Minibike' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'GARBA' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY FIRE' OR
[VEHICLE_TYPE_CODE_1] = 'STREE' OR
[VEHICLE_TYPE_CODE_1] = 'FORD' OR
[VEHICLE_TYPE_CODE_1] = 'Van Camper' OR
[VEHICLE_TYPE_CODE_1] = 'posta' OR
[VEHICLE_TYPE_CODE_1] = 'Motorized Home' OR
[VEHICLE_TYPE_CODE_1] = 'motor' OR
[VEHICLE_TYPE_CODE_1] = 'GARBAGE TR' OR
[VEHICLE_TYPE_CODE_1] = 'FLAT' OR
[VEHICLE_TYPE_CODE_1] = 'TANK' OR
[VEHICLE_TYPE_CODE_1] = 'Self' OR
[VEHICLE_TYPE_CODE_1] = 'Minicycle' OR
[VEHICLE_TYPE_CODE_1] = 'RV' OR
[VEHICLE_TYPE_CODE_1] = 'WAGON' OR
[VEHICLE_TYPE_CODE_1] = 'SANIT' OR
[VEHICLE_TYPE_CODE_1] = 'picku' OR
[VEHICLE_TYPE_CODE_1] = 'Hopper' OR
[VEHICLE_TYPE_CODE_1] = 'dump truck' OR
[VEHICLE_TYPE_CODE_1] = 'Pick up tr' OR
[VEHICLE_TYPE_CODE_1] = 'FREIG' OR
[VEHICLE_TYPE_CODE_1] = 'TRL' OR
[VEHICLE_TYPE_CODE_1] = 'FORKLIFT' OR
[VEHICLE_TYPE_CODE_1] = 'MTA BUS' OR
[VEHICLE_TYPE_CODE_1] = 'TRAC' OR
[VEHICLE_TYPE_CODE_1] = 'TRK' OR
[VEHICLE_TYPE_CODE_1] = 'PICKUP' OR
[VEHICLE_TYPE_CODE_1] = 'FORK' OR
[VEHICLE_TYPE_CODE_1] = 'UTILITY' OR
[VEHICLE_TYPE_CODE_1] = 'Tow' OR
[VEHICLE_TYPE_CODE_1] = 'MACK' OR
[VEHICLE_TYPE_CODE_1] = 'REFG' OR
[VEHICLE_TYPE_CODE_1] = 'Sprinter V' OR
[VEHICLE_TYPE_CODE_1] = 'backh' OR
[VEHICLE_TYPE_CODE_1] = 'Fork lift' OR
[VEHICLE_TYPE_CODE_1] = 'USPS truck' OR
[VEHICLE_TYPE_CODE_1] = 'US PO' OR
[VEHICLE_TYPE_CODE_1] = 'SUV' OR
[VEHICLE_TYPE_CODE_1] = 'GOLF CART' OR
[VEHICLE_TYPE_CODE_1] = 'ROAD SWEEP' OR
[VEHICLE_TYPE_CODE_1] = 'C1' OR
[VEHICLE_TYPE_CODE_1] = 'Sanitation' OR
[VEHICLE_TYPE_CODE_1] = 'passenger' OR
[VEHICLE_TYPE_CODE_1] = 'Vanette' OR
[VEHICLE_TYPE_CODE_1] = 'van t' OR
[VEHICLE_TYPE_CODE_1] = 'OMR' OR
[VEHICLE_TYPE_CODE_1] = 'MTA B' OR
[VEHICLE_TYPE_CODE_1] = 'VAN TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'Mail' OR
[VEHICLE_TYPE_CODE_1] = 'SEMI' OR
[VEHICLE_TYPE_CODE_1] = 'POWER' OR
[VEHICLE_TYPE_CODE_1] = 'Golf' OR
[VEHICLE_TYPE_CODE_1] = 'FIRE ENGIN' OR
[VEHICLE_TYPE_CODE_1] = 'PSD' OR
[VEHICLE_TYPE_CODE_1] = 'MOTOR SCOO' OR
[VEHICLE_TYPE_CODE_1] = 'DELIVERY T' OR
[VEHICLE_TYPE_CODE_1] = 'crane' OR
[VEHICLE_TYPE_CODE_1] = 'road' OR
[VEHICLE_TYPE_CODE_1] = 'SELF INSUR' OR
[VEHICLE_TYPE_CODE_1] = 'OMT' OR
[VEHICLE_TYPE_CODE_1] = 'Tractor Tr' OR
[VEHICLE_TYPE_CODE_1] = 'Const' OR
[VEHICLE_TYPE_CODE_1] = 'Glass Rack' OR
[VEHICLE_TYPE_CODE_1] = 'Livestock Rack' OR
[VEHICLE_TYPE_CODE_1] = 'FLATB' OR
[VEHICLE_TYPE_CODE_1] = 'Pickup tru' OR
[VEHICLE_TYPE_CODE_1] = 'Well Driller' OR
[VEHICLE_TYPE_CODE_1] = 'ELECTRIC S' OR
[VEHICLE_TYPE_CODE_1] = 'STAK' OR
[VEHICLE_TYPE_CODE_1] = 'PC' OR
[VEHICLE_TYPE_CODE_1] = 'N/A' OR
[VEHICLE_TYPE_CODE_1] = 'SPC' OR
[VEHICLE_TYPE_CODE_1] = 'COMM' OR
[VEHICLE_TYPE_CODE_1] = 'UHAUL' OR
[VEHICLE_TYPE_CODE_1] = 'P/SH' OR
[VEHICLE_TYPE_CODE_1] = 'STREET SWE' OR
[VEHICLE_TYPE_CODE_1] = 'CEMEN' OR
[VEHICLE_TYPE_CODE_1] = 'UTILITY VE' OR
[VEHICLE_TYPE_CODE_1] = 'Delivery' OR
[VEHICLE_TYPE_CODE_1] = 'SPRIN' OR
[VEHICLE_TYPE_CODE_1] = 'TRACTOR' OR
[VEHICLE_TYPE_CODE_1] = 'tk' OR
[VEHICLE_TYPE_CODE_1] = 'MAIL TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'Power shov' OR
[VEHICLE_TYPE_CODE_1] = 'F550' OR
[VEHICLE_TYPE_CODE_1] = 'OML' OR
[VEHICLE_TYPE_CODE_1] = 'Log' OR
[VEHICLE_TYPE_CODE_1] = 'Food' OR
[VEHICLE_TYPE_CODE_1] = 'PICK-' OR
[VEHICLE_TYPE_CODE_1] = 'utility tr' OR
[VEHICLE_TYPE_CODE_1] = 'CITY' OR
[VEHICLE_TYPE_CODE_1] = 'YELLO' OR
[VEHICLE_TYPE_CODE_1] = 'gas scoote' OR
[VEHICLE_TYPE_CODE_1] = 'Cargo' OR
[VEHICLE_TYPE_CODE_1] = 'WHITE' OR
[VEHICLE_TYPE_CODE_1] = 'Enclosed Body - Nonremovable Enclosure' OR
[VEHICLE_TYPE_CODE_1] = 'government' OR
[VEHICLE_TYPE_CODE_1] = 'AMBULETTE' OR
[VEHICLE_TYPE_CODE_1] = 'MTA' OR
[VEHICLE_TYPE_CODE_1] = 'rmp' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY EMS' OR
[VEHICLE_TYPE_CODE_1] = 'MINI' OR
[VEHICLE_TYPE_CODE_1] = 'PASSE' OR
[VEHICLE_TYPE_CODE_1] = 'NYPD' OR
[VEHICLE_TYPE_CODE_1] = 'SUBURBAN' OR
[VEHICLE_TYPE_CODE_1] = 'Pass' OR
[VEHICLE_TYPE_CODE_1] = 'US POSTAL' OR
[VEHICLE_TYPE_CODE_1] = 'NYS Ambula' OR
[VEHICLE_TYPE_CODE_1] = 'OMNIB' OR
[VEHICLE_TYPE_CODE_1] = 'Postal tru' OR
[VEHICLE_TYPE_CODE_1] = 'Horse' OR
[VEHICLE_TYPE_CODE_1] = 'BOBCA' OR
[VEHICLE_TYPE_CODE_1] = 'E bik' OR
[VEHICLE_TYPE_CODE_1] = 'TRLR' OR
[VEHICLE_TYPE_CODE_1] = 'EMS' OR
[VEHICLE_TYPE_CODE_1] = 'work' OR
[VEHICLE_TYPE_CODE_1] = 'tr' OR
[VEHICLE_TYPE_CODE_1] = 'Dirt Bike' OR
[VEHICLE_TYPE_CODE_1] = 'Enclosed Body - Removable Enclosure' OR
[VEHICLE_TYPE_CODE_1] = 'GAS MOPED' OR
[VEHICLE_TYPE_CODE_1] = 'ebike' OR
[VEHICLE_TYPE_CODE_1] = 'SKATEBOARD' OR
[VEHICLE_TYPE_CODE_1] = 'BOX' OR
[VEHICLE_TYPE_CODE_1] = 'acces' OR
[VEHICLE_TYPE_CODE_1] = 'FLATBED' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY Firet' OR
[VEHICLE_TYPE_CODE_1] = 'HINO' OR
[VEHICLE_TYPE_CODE_1] = 'Cargo van' OR
[VEHICLE_TYPE_CODE_1] = 'G COM' OR
[VEHICLE_TYPE_CODE_1] = 'COURIER' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY LADDE' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY ENGIN' OR
[VEHICLE_TYPE_CODE_1] = 'SUBUR' OR
[VEHICLE_TYPE_CODE_1] = 'Mopd' OR
[VEHICLE_TYPE_CODE_1] = 'DELIVERY V' OR
[VEHICLE_TYPE_CODE_1] = 'FORD VAN' OR
[VEHICLE_TYPE_CODE_1] = 'Excavator' OR
[VEHICLE_TYPE_CODE_1] = 'REFRI' OR
[VEHICLE_TYPE_CODE_1] = 'AMBULENCE' OR
[VEHICLE_TYPE_CODE_1] = 'WORK VAN' OR
[VEHICLE_TYPE_CODE_1] = 'CO' OR
[VEHICLE_TYPE_CODE_1] = 'PICK-UP TR' OR
[VEHICLE_TYPE_CODE_1] = 'Cement tru' OR
[VEHICLE_TYPE_CODE_1] = 'USPS MAIL' OR
[VEHICLE_TYPE_CODE_1] = 'mc' OR
[VEHICLE_TYPE_CODE_1] = 'mcy' OR
[VEHICLE_TYPE_CODE_1] = 'movin' OR
[VEHICLE_TYPE_CODE_1] = 'JEEP' OR
[VEHICLE_TYPE_CODE_1] = 'BULLD' OR
[VEHICLE_TYPE_CODE_1] = 'Pick-Up' OR
[VEHICLE_TYPE_CODE_1] = 'ICE C' OR
[VEHICLE_TYPE_CODE_1] = 'Motorscoot' OR
[VEHICLE_TYPE_CODE_1] = 'E scooter' OR
[VEHICLE_TYPE_CODE_1] = 'CMIX' OR
[VEHICLE_TYPE_CODE_1] = 'UT' OR
[VEHICLE_TYPE_CODE_1] = 'Fedex' OR
[VEHICLE_TYPE_CODE_1] = 'excav' OR
[VEHICLE_TYPE_CODE_1] = 'TRANS' OR
[VEHICLE_TYPE_CODE_1] = 'MACK TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'U-Hau' OR
[VEHICLE_TYPE_CODE_1] = 'unkow' OR
[VEHICLE_TYPE_CODE_1] = 'Inter' OR
[VEHICLE_TYPE_CODE_1] = 'C3' OR
[VEHICLE_TYPE_CODE_1] = 'freight' OR
[VEHICLE_TYPE_CODE_1] = 'FREIGHTLIN' OR
[VEHICLE_TYPE_CODE_1] = 'SWEEP' OR
[VEHICLE_TYPE_CODE_1] = 'Rescu' OR
[VEHICLE_TYPE_CODE_1] = 'COURI' OR
[VEHICLE_TYPE_CODE_1] = 'back' OR
[VEHICLE_TYPE_CODE_1] = 'EMS bus' OR
[VEHICLE_TYPE_CODE_1] = 'rd/s' OR
[VEHICLE_TYPE_CODE_1] = 'VAN/T' OR
[VEHICLE_TYPE_CODE_1] = 'LIGHT' OR
[VEHICLE_TYPE_CODE_1] = 'REP' OR
[VEHICLE_TYPE_CODE_1] = 'TANKE' OR
[VEHICLE_TYPE_CODE_1] = 'CATER' OR
[VEHICLE_TYPE_CODE_1] = 'TOWER' OR
[VEHICLE_TYPE_CODE_1] = 'FORD TRANS' OR
[VEHICLE_TYPE_CODE_1] = 'gator' OR
[VEHICLE_TYPE_CODE_1] = 'BOBCAT' OR
[VEHICLE_TYPE_CODE_1] = 'DIRT' OR
[VEHICLE_TYPE_CODE_1] = 'LIVER' OR
[VEHICLE_TYPE_CODE_1] = 'LADDER TRU' OR
[VEHICLE_TYPE_CODE_1] = 'UPS T' OR
[VEHICLE_TYPE_CODE_1] = 'GOVER' OR
[VEHICLE_TYPE_CODE_1] = 'WINNE' OR
[VEHICLE_TYPE_CODE_1] = 'UPS TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'MOBIL' OR
[VEHICLE_TYPE_CODE_1] = 'A' OR
[VEHICLE_TYPE_CODE_1] = 'EMS TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'RENTA' OR
[VEHICLE_TYPE_CODE_1] = 'Trc' OR
[VEHICLE_TYPE_CODE_1] = 'Horse trai' OR
[VEHICLE_TYPE_CODE_1] = 'TLC' OR
[VEHICLE_TYPE_CODE_1] = 'Veriz' OR
[VEHICLE_TYPE_CODE_1] = 'NYC SANITA' OR
[VEHICLE_TYPE_CODE_1] = 'TRACK' OR
[VEHICLE_TYPE_CODE_1] = 'skate' OR
[VEHICLE_TYPE_CODE_1] = 'FIRE APPAR' OR
[VEHICLE_TYPE_CODE_1] = 'R/V' OR
[VEHICLE_TYPE_CODE_1] = 'TL' OR
[VEHICLE_TYPE_CODE_1] = 'Dodge' OR
[VEHICLE_TYPE_CODE_1] = 'FOOD TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'HRSE' OR
[VEHICLE_TYPE_CODE_1] = 'D3' OR
[VEHICLE_TYPE_CODE_1] = 'Grain' OR
[VEHICLE_TYPE_CODE_1] = 'SCOM' OR
[VEHICLE_TYPE_CODE_1] = 'SS' OR
[VEHICLE_TYPE_CODE_1] = 'UTV' OR
[VEHICLE_TYPE_CODE_1] = 'MOPAD' OR
[VEHICLE_TYPE_CODE_1] = 'CASE' OR
[VEHICLE_TYPE_CODE_1] = 'SE' OR
[VEHICLE_TYPE_CODE_1] = '4D' OR
[VEHICLE_TYPE_CODE_1] = 'fd tr' OR
[VEHICLE_TYPE_CODE_1] = 'BOOM LIFT' OR
[VEHICLE_TYPE_CODE_1] = 'Marke' OR
[VEHICLE_TYPE_CODE_1] = 'CHEVY' OR
[VEHICLE_TYPE_CODE_1] = 'L1' OR
[VEHICLE_TYPE_CODE_1] = 'house on w' OR
[VEHICLE_TYPE_CODE_1] = 'APPOR' OR
[VEHICLE_TYPE_CODE_1] = 'spec' OR
[VEHICLE_TYPE_CODE_1] = 'PKUP' OR
[VEHICLE_TYPE_CODE_1] = 'PASSANGER' OR
[VEHICLE_TYPE_CODE_1] = 'MOTOR HOME' OR
[VEHICLE_TYPE_CODE_1] = 'U-Haul' OR
[VEHICLE_TYPE_CODE_1] = 'ECONOLINE' OR
[VEHICLE_TYPE_CODE_1] = '4DS' OR
[VEHICLE_TYPE_CODE_1] = 'USPS POSTA' OR
[VEHICLE_TYPE_CODE_1] = '3 WHE' OR
[VEHICLE_TYPE_CODE_1] = 'LIMOU' OR
[VEHICLE_TYPE_CODE_1] = 'FRIEG' OR
[VEHICLE_TYPE_CODE_1] = 'VMS' OR
[VEHICLE_TYPE_CODE_1] = '1' OR
[VEHICLE_TYPE_CODE_1] = '4dsd' OR
[VEHICLE_TYPE_CODE_1] = '15 Pa' OR
[VEHICLE_TYPE_CODE_1] = 'Mini Van' OR
[VEHICLE_TYPE_CODE_1] = 'ECONO' OR
[VEHICLE_TYPE_CODE_1] = 'Backhoe' OR
[VEHICLE_TYPE_CODE_1] = 'FRHT' OR
[VEHICLE_TYPE_CODE_1] = 'NISSA' OR
[VEHICLE_TYPE_CODE_1] = 'AMBULACE' OR
[VEHICLE_TYPE_CODE_1] = 'PAYLO' OR
[VEHICLE_TYPE_CODE_1] = 'Motorized' OR
[VEHICLE_TYPE_CODE_1] = 'SEMI-' OR
[VEHICLE_TYPE_CODE_1] = 'commerical' OR
[VEHICLE_TYPE_CODE_1] = 'dumps' OR
[VEHICLE_TYPE_CODE_1] = 'FED E' OR
[VEHICLE_TYPE_CODE_1] = 'MINIV' OR
[VEHICLE_TYPE_CODE_1] = 'OIL T' OR
[VEHICLE_TYPE_CODE_1] = 'Electric m' OR
[VEHICLE_TYPE_CODE_1] = 'St' OR
[VEHICLE_TYPE_CODE_1] = 'GEICO' OR
[VEHICLE_TYPE_CODE_1] = 'AMBULANE' OR
[VEHICLE_TYPE_CODE_1] = 'CON ED TRU' OR
[VEHICLE_TYPE_CODE_1] = 'SW' OR
[VEHICLE_TYPE_CODE_1] = 'C2' OR
[VEHICLE_TYPE_CODE_1] = 'FLEET' OR
[VEHICLE_TYPE_CODE_1] = 'Post offic' OR
[VEHICLE_TYPE_CODE_1] = 'NYCHA' OR
[VEHICLE_TYPE_CODE_1] = 'BoxTr' OR
[VEHICLE_TYPE_CODE_1] = 'e com' OR
[VEHICLE_TYPE_CODE_1] = 'TF' OR
[VEHICLE_TYPE_CODE_1] = 'BUCKE' OR
[VEHICLE_TYPE_CODE_1] = 'Postal ser' OR
[VEHICLE_TYPE_CODE_1] = 'MTA transi' OR
[VEHICLE_TYPE_CODE_1] = 'DOLLY' OR
[VEHICLE_TYPE_CODE_1] = 'HEAVY' OR
[VEHICLE_TYPE_CODE_1] = 'NYPD TOW T' OR
[VEHICLE_TYPE_CODE_1] = 'Pavin' OR
[VEHICLE_TYPE_CODE_1] = 'NYC AMBULA' OR
[VEHICLE_TYPE_CODE_1] = 'PUMP' OR
[VEHICLE_TYPE_CODE_1] = 'TOWTR' OR
[VEHICLE_TYPE_CODE_1] = 'NOT I' OR
[VEHICLE_TYPE_CODE_1] = 'Grumman LL' OR
[VEHICLE_TYPE_CODE_1] = 'SMART' OR
[VEHICLE_TYPE_CODE_1] = '50cc Scoot' OR
[VEHICLE_TYPE_CODE_1] = 'STREET CLE' OR
[VEHICLE_TYPE_CODE_1] = 'FRONT' OR
[VEHICLE_TYPE_CODE_1] = 'FUEL' OR
[VEHICLE_TYPE_CODE_1] = 'RGS' OR
[VEHICLE_TYPE_CODE_1] = 'SCOO' OR
[VEHICLE_TYPE_CODE_1] = 'Access-A-R' OR
[VEHICLE_TYPE_CODE_1] = 'DODGE RAM' OR
[VEHICLE_TYPE_CODE_1] = 'amazon tru' OR
[VEHICLE_TYPE_CODE_1] = 'Wheel' OR
[VEHICLE_TYPE_CODE_1] = 'truck trai' OR
[VEHICLE_TYPE_CODE_1] = 'I1' OR
[VEHICLE_TYPE_CODE_1] = 'CART' OR
[VEHICLE_TYPE_CODE_1] = 'ESU T' OR
[VEHICLE_TYPE_CODE_1] = '4door' OR
[VEHICLE_TYPE_CODE_1] = 'Bicyc' OR
[VEHICLE_TYPE_CODE_1] = 'FOOD CART' OR
[VEHICLE_TYPE_CODE_1] = 'FD Ambulan' OR
[VEHICLE_TYPE_CODE_1] = 'PEDIC' OR
[VEHICLE_TYPE_CODE_1] = 'SWT' OR
[VEHICLE_TYPE_CODE_1] = 'BS' OR
[VEHICLE_TYPE_CODE_1] = 'Omnibus' OR
[VEHICLE_TYPE_CODE_1] = 'Ram' OR
[VEHICLE_TYPE_CODE_1] = 'Budge' OR
[VEHICLE_TYPE_CODE_1] = 'Dot' OR
[VEHICLE_TYPE_CODE_1] = 'd1' OR
[VEHICLE_TYPE_CODE_1] = 'Mopped' OR
[VEHICLE_TYPE_CODE_1] = 'Schoolbus' OR
[VEHICLE_TYPE_CODE_1] = 'SEGWA' OR
[VEHICLE_TYPE_CODE_1] = 'NEW Y' OR
[VEHICLE_TYPE_CODE_1] = 'Constructi' OR
[VEHICLE_TYPE_CODE_1] = 'E bike' OR
[VEHICLE_TYPE_CODE_1] = 'PSH' OR
[VEHICLE_TYPE_CODE_1] = '3-whe' OR
[VEHICLE_TYPE_CODE_1] = 'City Owned' OR
[VEHICLE_TYPE_CODE_1] = 'NAVIG' OR
[VEHICLE_TYPE_CODE_1] = 'Skywatch' OR
[VEHICLE_TYPE_CODE_1] = 'SUB' OR
[VEHICLE_TYPE_CODE_1] = 'na' OR
[VEHICLE_TYPE_CODE_1] = 'USPS VAN' OR
[VEHICLE_TYPE_CODE_1] = 'DUMPT' OR
[VEHICLE_TYPE_CODE_1] = 'Subr' OR
[VEHICLE_TYPE_CODE_1] = 'plow' OR
[VEHICLE_TYPE_CODE_1] = 'VAV' OR
[VEHICLE_TYPE_CODE_1] = 'NYC F' OR
[VEHICLE_TYPE_CODE_1] = 'US' OR
[VEHICLE_TYPE_CODE_1] = 'fed ex tru' OR
[VEHICLE_TYPE_CODE_1] = 'NYC FIRE T' OR
[VEHICLE_TYPE_CODE_1] = 'FREIGHT TR' OR
[VEHICLE_TYPE_CODE_1] = 'toyot' OR
[VEHICLE_TYPE_CODE_1] = 'SCOOTER GA' OR
[VEHICLE_TYPE_CODE_1] = 'PERM' OR
[VEHICLE_TYPE_CODE_1] = 'Van (Trans' OR
[VEHICLE_TYPE_CODE_1] = 'NYC' OR
[VEHICLE_TYPE_CODE_1] = 'TCN' OR
[VEHICLE_TYPE_CODE_1] = 'KENWO' OR
[VEHICLE_TYPE_CODE_1] = 'ladde' OR
[VEHICLE_TYPE_CODE_1] = 'USPS VEHIC' OR
[VEHICLE_TYPE_CODE_1] = 'APP' OR
[VEHICLE_TYPE_CODE_1] = 'vespa' OR
[VEHICLE_TYPE_CODE_1] = 'FLATBED TO' OR
[VEHICLE_TYPE_CODE_1] = 'standing s' OR
[VEHICLE_TYPE_CODE_1] = '12 Pa' OR
[VEHICLE_TYPE_CODE_1] = 'BOOM' OR
[VEHICLE_TYPE_CODE_1] = 'VAN W' OR
[VEHICLE_TYPE_CODE_1] = 'Mailtruck' OR
[VEHICLE_TYPE_CODE_1] = 'Horse carr' OR
[VEHICLE_TYPE_CODE_1] = 'NYC TRANSI' OR
[VEHICLE_TYPE_CODE_1] = 'LEFT' OR
[VEHICLE_TYPE_CODE_1] = 'G TOW' OR
[VEHICLE_TYPE_CODE_1] = 'Detached t' OR
[VEHICLE_TYPE_CODE_1] = 'EMS A' OR
[VEHICLE_TYPE_CODE_1] = 'VAN/TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'NYC D' OR
[VEHICLE_TYPE_CODE_1] = 'Can' OR
[VEHICLE_TYPE_CODE_1] = 'Bucket Tru' OR
[VEHICLE_TYPE_CODE_1] = 'EMT Ambula' OR
[VEHICLE_TYPE_CODE_1] = 'GLBEN' OR
[VEHICLE_TYPE_CODE_1] = 'VPG' OR
[VEHICLE_TYPE_CODE_1] = 'FLAT/' OR
[VEHICLE_TYPE_CODE_1] = 'EMS T' OR
[VEHICLE_TYPE_CODE_1] = 'USPOS' OR
[VEHICLE_TYPE_CODE_1] = 'sterl' OR
[VEHICLE_TYPE_CODE_1] = 'ABULANCE' OR
[VEHICLE_TYPE_CODE_1] = '4DR' OR
[VEHICLE_TYPE_CODE_1] = 'SPRINTER' OR
[VEHICLE_TYPE_CODE_1] = 'SEMI TRAIL' OR
[VEHICLE_TYPE_CODE_1] = 'work truck' OR
[VEHICLE_TYPE_CODE_1] = 'E SCO' OR
[VEHICLE_TYPE_CODE_1] = 'E AMB' OR
[VEHICLE_TYPE_CODE_1] = 'PUMPER' OR
[VEHICLE_TYPE_CODE_1] = 'Ice Cream' OR
[VEHICLE_TYPE_CODE_1] = '18 WHEELER' OR
[VEHICLE_TYPE_CODE_1] = 'LMB' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY EMS V' OR
[VEHICLE_TYPE_CODE_1] = 'OMS' OR
[VEHICLE_TYPE_CODE_1] = 'BK' OR
[VEHICLE_TYPE_CODE_1] = 'EMS Ambula' OR
[VEHICLE_TYPE_CODE_1] = 'U HAU' OR
[VEHICLE_TYPE_CODE_1] = 'ENGIN' OR
[VEHICLE_TYPE_CODE_1] = 'CITY OF NE' OR
[VEHICLE_TYPE_CODE_1] = 'SP PURPOSE' OR
[VEHICLE_TYPE_CODE_1] = 'MINI BUS' OR
[VEHICLE_TYPE_CODE_1] = 'concr' OR
[VEHICLE_TYPE_CODE_1] = 'LTR' OR
[VEHICLE_TYPE_CODE_1] = 'DIRTB' OR
[VEHICLE_TYPE_CODE_1] = 'LIGHT TRAI' OR
[VEHICLE_TYPE_CODE_1] = 'amulance' OR
[VEHICLE_TYPE_CODE_1] = 'house' OR
[VEHICLE_TYPE_CODE_1] = 'GRAY' OR
[VEHICLE_TYPE_CODE_1] = 'G PSD' OR
[VEHICLE_TYPE_CODE_1] = 'CHEV' OR
[VEHICLE_TYPE_CODE_1] = 'FORD SPRIN' OR
[VEHICLE_TYPE_CODE_1] = 'SUBN - AMB' OR
[VEHICLE_TYPE_CODE_1] = 'TRT' OR
[VEHICLE_TYPE_CODE_1] = 'carri' OR
[VEHICLE_TYPE_CODE_1] = '5X8 T' OR
[VEHICLE_TYPE_CODE_1] = 'Postal Box' OR
[VEHICLE_TYPE_CODE_1] = 'RUBBE' OR
[VEHICLE_TYPE_CODE_1] = 'Car C' OR
[VEHICLE_TYPE_CODE_1] = 'LADDER CO' OR
[VEHICLE_TYPE_CODE_1] = 'postal van' OR
[VEHICLE_TYPE_CODE_1] = '2 DOO' OR
[VEHICLE_TYPE_CODE_1] = '�MBU' OR
[VEHICLE_TYPE_CODE_1] = 'Razor Scoo' OR
[VEHICLE_TYPE_CODE_1] = 'DIESE' OR
[VEHICLE_TYPE_CODE_1] = 'NonMotordS' OR
[VEHICLE_TYPE_CODE_1] = 'Bucketload' OR
[VEHICLE_TYPE_CODE_1] = 'Shove' OR
[VEHICLE_TYPE_CODE_1] = 'NYC FDNY #' OR
[VEHICLE_TYPE_CODE_1] = 'COM TRANS' OR
[VEHICLE_TYPE_CODE_1] = 'ARMY' OR
[VEHICLE_TYPE_CODE_1] = 'Cat 9' OR
[VEHICLE_TYPE_CODE_1] = 'TRALI' OR
[VEHICLE_TYPE_CODE_1] = 'Red moped' OR
[VEHICLE_TYPE_CODE_1] = 'GREEN' OR
[VEHICLE_TYPE_CODE_1] = 'ELE MOTORC' OR
[VEHICLE_TYPE_CODE_1] = 'F550 ESU R' OR
[VEHICLE_TYPE_CODE_1] = 'E - B' OR
[VEHICLE_TYPE_CODE_1] = 'BOBCAT FOR' OR
[VEHICLE_TYPE_CODE_1] = 'FEIG' OR
[VEHICLE_TYPE_CODE_1] = 'NYNJ RAIL' OR
[VEHICLE_TYPE_CODE_1] = 'MOTOR SKAT' OR
[VEHICLE_TYPE_CODE_1] = 'SUBN WHI' OR
[VEHICLE_TYPE_CODE_1] = 'Farm' OR
[VEHICLE_TYPE_CODE_1] = 'SONATA' OR
[VEHICLE_TYPE_CODE_1] = '994' OR
[VEHICLE_TYPE_CODE_1] = 'Gator 4x4' OR
[VEHICLE_TYPE_CODE_1] = 'Fire Truvk' OR
[VEHICLE_TYPE_CODE_1] = 'Yale Fork' OR
[VEHICLE_TYPE_CODE_1] = 'red t' OR
[VEHICLE_TYPE_CODE_1] = 'dp' OR
[VEHICLE_TYPE_CODE_1] = 'nyc EMS' OR
[VEHICLE_TYPE_CODE_1] = 'JOHN DEERE' OR
[VEHICLE_TYPE_CODE_1] = 'Lime Scoot' OR
[VEHICLE_TYPE_CODE_1] = 'REPAI' OR
[VEHICLE_TYPE_CODE_1] = 'YW SCHOOL' OR
[VEHICLE_TYPE_CODE_1] = 'Attac' OR
[VEHICLE_TYPE_CODE_1] = 'CAT P' OR
[VEHICLE_TYPE_CODE_1] = 'OTH' OR
[VEHICLE_TYPE_CODE_1] = 'Hearse' OR
[VEHICLE_TYPE_CODE_1] = 'DUMPSTER T' OR
[VEHICLE_TYPE_CODE_1] = 'TRAILEE' OR
[VEHICLE_TYPE_CODE_1] = 'Leased amb' OR
[VEHICLE_TYPE_CODE_1] = 'POWER LADD' OR
[VEHICLE_TYPE_CODE_1] = 'ST150' OR
[VEHICLE_TYPE_CODE_1] = '1S' OR
[VEHICLE_TYPE_CODE_1] = 'EAMB' OR
[VEHICLE_TYPE_CODE_1] = 'TTRAILER' OR
[VEHICLE_TYPE_CODE_1] = 'MTA C' OR
[VEHICLE_TYPE_CODE_1] = 'E.M.S' OR
[VEHICLE_TYPE_CODE_1] = 'USPS #7530' OR
[VEHICLE_TYPE_CODE_1] = 'E-MOT' OR
[VEHICLE_TYPE_CODE_1] = 'amdu' OR
[VEHICLE_TYPE_CODE_1] = 'P PSD' OR
[VEHICLE_TYPE_CODE_1] = 'MO-PED' OR
[VEHICLE_TYPE_CODE_1] = 'AMBUKANCE' OR
[VEHICLE_TYPE_CODE_1] = 'REFR' OR
[VEHICLE_TYPE_CODE_1] = 'SELF-' OR
[VEHICLE_TYPE_CODE_1] = 'MOVING VAN' OR
[VEHICLE_TYPE_CODE_1] = 'PETIT CAB' OR
[VEHICLE_TYPE_CODE_1] = 'Honda HRV' OR
[VEHICLE_TYPE_CODE_1] = 'ford econo' OR
[VEHICLE_TYPE_CODE_1] = 'comm.' OR
[VEHICLE_TYPE_CODE_1] = 'VA' OR
[VEHICLE_TYPE_CODE_1] = 'ESU RESCUE' OR
[VEHICLE_TYPE_CODE_1] = 'STATE' OR
[VEHICLE_TYPE_CODE_1] = 'VAN A' OR
[VEHICLE_TYPE_CODE_1] = 'Livery Bus' OR
[VEHICLE_TYPE_CODE_1] = '3 doo' OR
[VEHICLE_TYPE_CODE_1] = 'FRE' OR
[VEHICLE_TYPE_CODE_1] = 'leu' OR
[VEHICLE_TYPE_CODE_1] = 'EMS FDNY B' OR
[VEHICLE_TYPE_CODE_1] = 'GOLFCART' OR
[VEHICLE_TYPE_CODE_1] = 'Quality tr' OR
[VEHICLE_TYPE_CODE_1] = 'RAZOR150 M' OR
[VEHICLE_TYPE_CODE_1] = 'nycta' OR
[VEHICLE_TYPE_CODE_1] = 'dsny' OR
[VEHICLE_TYPE_CODE_1] = 'DRILL RIG' OR
[VEHICLE_TYPE_CODE_1] = 'REF BOX TR' OR
[VEHICLE_TYPE_CODE_1] = 'X Amb' OR
[VEHICLE_TYPE_CODE_1] = 'FREIGHT VA' OR
[VEHICLE_TYPE_CODE_1] = 'NYCHA Van' OR
[VEHICLE_TYPE_CODE_1] = 'MECHANICAL' OR
[VEHICLE_TYPE_CODE_1] = 'EMERGENCY' OR
[VEHICLE_TYPE_CODE_1] = 'NS AM' OR
[VEHICLE_TYPE_CODE_1] = 'CATIP' OR
[VEHICLE_TYPE_CODE_1] = 'Rescue Tru' OR
[VEHICLE_TYPE_CODE_1] = 'MAC T' OR
[VEHICLE_TYPE_CODE_1] = 'ABULA' OR
[VEHICLE_TYPE_CODE_1] = 'H3' OR
[VEHICLE_TYPE_CODE_1] = 'DEPARTMENT' OR
[VEHICLE_TYPE_CODE_1] = 'SCHOOL  BU' OR
[VEHICLE_TYPE_CODE_1] = 'Ford picku' OR
[VEHICLE_TYPE_CODE_1] = 'icecr' OR
[VEHICLE_TYPE_CODE_1] = 'Sweeper' OR
[VEHICLE_TYPE_CODE_1] = 'ESCOOTER S' OR
[VEHICLE_TYPE_CODE_1] = 'FREIGHT FL' OR
[VEHICLE_TYPE_CODE_1] = 'NY CITY MT' OR
[VEHICLE_TYPE_CODE_1] = 'FEDEX TRUC' OR
[VEHICLE_TYPE_CODE_1] = 'FLAT-' OR
[VEHICLE_TYPE_CODE_1] = 'BKHOE' OR
[VEHICLE_TYPE_CODE_1] = 'Combinatio' OR
[VEHICLE_TYPE_CODE_1] = 'SPR' OR
[VEHICLE_TYPE_CODE_1] = 'ALL TERRAI' OR
[VEHICLE_TYPE_CODE_1] = 'SELF-INSUR' OR
[VEHICLE_TYPE_CODE_1] = 'HORSE DRAW' OR
[VEHICLE_TYPE_CODE_1] = 'TRANSPORTE' OR
[VEHICLE_TYPE_CODE_1] = 'MINIVAN' OR
[VEHICLE_TYPE_CODE_1] = 'NYC PARKS' OR
[VEHICLE_TYPE_CODE_1] = '18 WH' OR
[VEHICLE_TYPE_CODE_1] = 'PU' OR
[VEHICLE_TYPE_CODE_1] = 'NT TR' OR
[VEHICLE_TYPE_CODE_1] = 'CONVE' OR
[VEHICLE_TYPE_CODE_1] = 'gokar' OR
[VEHICLE_TYPE_CODE_1] = 'TOWMA' OR
[VEHICLE_TYPE_CODE_1] = 'moped scoo' OR
[VEHICLE_TYPE_CODE_1] = 'Backhoe Lo' OR
[VEHICLE_TYPE_CODE_1] = 'east' OR
[VEHICLE_TYPE_CODE_1] = 'VOLVO' OR
[VEHICLE_TYPE_CODE_1] = 'Trolley ri' OR
[VEHICLE_TYPE_CODE_1] = 'YELLOW TAX' OR
[VEHICLE_TYPE_CODE_1] = 'wag' OR
[VEHICLE_TYPE_CODE_1] = 'TOW-TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK/VAN' OR
[VEHICLE_TYPE_CODE_1] = 'FRONT LOAD' OR
[VEHICLE_TYPE_CODE_1] = 'CAT FORKLI' OR
[VEHICLE_TYPE_CODE_1] = 'GOV V' OR
[VEHICLE_TYPE_CODE_1] = 'USPS #6530' OR
[VEHICLE_TYPE_CODE_1] = 'UTILITY WH' OR
[VEHICLE_TYPE_CODE_1] = 'MINI SCHOO' OR
[VEHICLE_TYPE_CODE_1] = 'FIRET TRUC' OR
[VEHICLE_TYPE_CODE_1] = 'TRANSPORT' OR
[VEHICLE_TYPE_CODE_1] = 'GOVENMENT' OR
[VEHICLE_TYPE_CODE_1] = 'commerial' OR
[VEHICLE_TYPE_CODE_1] = 'electronic' OR
[VEHICLE_TYPE_CODE_1] = 'Govt P/U T' OR
[VEHICLE_TYPE_CODE_1] = 'JETSKI' OR
[VEHICLE_TYPE_CODE_1] = 'YELLOWPOWE' OR
[VEHICLE_TYPE_CODE_1] = '2- to' OR
[VEHICLE_TYPE_CODE_1] = 'e skate bo' OR
[VEHICLE_TYPE_CODE_1] = '197209' OR
[VEHICLE_TYPE_CODE_1] = '4SEDN' OR
[VEHICLE_TYPE_CODE_1] = 'CAT' OR
[VEHICLE_TYPE_CODE_1] = 'Pickup tow' OR
[VEHICLE_TYPE_CODE_1] = 'F150XL PIC' OR
[VEHICLE_TYPE_CODE_1] = 'e-350' OR
[VEHICLE_TYPE_CODE_1] = 'REVEL' OR
[VEHICLE_TYPE_CODE_1] = 'EMRGN' OR
[VEHICLE_TYPE_CODE_1] = 'Snowmobile' OR
[VEHICLE_TYPE_CODE_1] = 'FLATBED FR' OR
[VEHICLE_TYPE_CODE_1] = 'SKID-' OR
[VEHICLE_TYPE_CODE_1] = 'mtr s' OR
[VEHICLE_TYPE_CODE_1] = 'POIS' OR
[VEHICLE_TYPE_CODE_1] = 'T/ CR' OR
[VEHICLE_TYPE_CODE_1] = 'bsd' OR
[VEHICLE_TYPE_CODE_1] = 'BOOM MOPED' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY Vehic' OR
[VEHICLE_TYPE_CODE_1] = 'PV HOLDING' OR
[VEHICLE_TYPE_CODE_1] = 'White Van' OR
[VEHICLE_TYPE_CODE_1] = '99999' OR
[VEHICLE_TYPE_CODE_1] = 'VAB' OR
[VEHICLE_TYPE_CODE_1] = 'Commer Veh' OR
[VEHICLE_TYPE_CODE_1] = 'COMM TRAIL' OR
[VEHICLE_TYPE_CODE_1] = 'Landscapin' OR
[VEHICLE_TYPE_CODE_1] = 'USPS/GOVT' OR
[VEHICLE_TYPE_CODE_1] = 'CATAPILLAR' OR
[VEHICLE_TYPE_CODE_1] = 'HOSRE' OR
[VEHICLE_TYPE_CODE_1] = 'PUSH SCOOT' OR
[VEHICLE_TYPE_CODE_1] = 'UNKNW' OR
[VEHICLE_TYPE_CODE_1] = 'ONE WHEEL' OR
[VEHICLE_TYPE_CODE_1] = 'AMABU' OR
[VEHICLE_TYPE_CODE_1] = 'santa' OR
[VEHICLE_TYPE_CODE_1] = 'Dumb Truck' OR
[VEHICLE_TYPE_CODE_1] = 'ESU REP' OR
[VEHICLE_TYPE_CODE_1] = 'CITYWIDE' OR
[VEHICLE_TYPE_CODE_1] = '7532433' OR
[VEHICLE_TYPE_CODE_1] = 'NYC MTA BU' OR
[VEHICLE_TYPE_CODE_1] = 'In Line Sk' OR
[VEHICLE_TYPE_CODE_1] = 'Nova' OR
[VEHICLE_TYPE_CODE_1] = 'MOT' OR
[VEHICLE_TYPE_CODE_1] = 'NTTRL' OR
[VEHICLE_TYPE_CODE_1] = 'sgws' OR
[VEHICLE_TYPE_CODE_1] = 'LADDER 34' OR
[VEHICLE_TYPE_CODE_1] = 'LIBER' OR
[VEHICLE_TYPE_CODE_1] = 'Station Wa' OR
[VEHICLE_TYPE_CODE_1] = 'A-ONE' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK VAN' OR
[VEHICLE_TYPE_CODE_1] = 'cm' OR
[VEHICLE_TYPE_CODE_1] = 'WHIT' OR
[VEHICLE_TYPE_CODE_1] = 'MAIL CARRI' OR
[VEHICLE_TYPE_CODE_1] = 'LIABITIY' OR
[VEHICLE_TYPE_CODE_1] = 'BROOM' OR
[VEHICLE_TYPE_CODE_1] = '2 TON' OR
[VEHICLE_TYPE_CODE_1] = 'Unmarked V' OR
[VEHICLE_TYPE_CODE_1] = 'HWH' OR
[VEHICLE_TYPE_CODE_1] = 'SPECIAL CO' OR
[VEHICLE_TYPE_CODE_1] = 'nat grid t' OR
[VEHICLE_TYPE_CODE_1] = 'MOTORHOME' OR
[VEHICLE_TYPE_CODE_1] = 'GEN  AMBUL' OR
[VEHICLE_TYPE_CODE_1] = 'FREE' OR
[VEHICLE_TYPE_CODE_1] = 'GOVT.' OR
[VEHICLE_TYPE_CODE_1] = 'PROGRESSIV' OR
[VEHICLE_TYPE_CODE_1] = 'LD' OR
[VEHICLE_TYPE_CODE_1] = 'MAXIM' OR
[VEHICLE_TYPE_CODE_1] = '2 wheel sc' OR
[VEHICLE_TYPE_CODE_1] = 'Sprinter W' OR
[VEHICLE_TYPE_CODE_1] = 'SC' OR
[VEHICLE_TYPE_CODE_1] = '4 axe' OR
[VEHICLE_TYPE_CODE_1] = 'KME/F' OR
[VEHICLE_TYPE_CODE_1] = 'FIRER' OR
[VEHICLE_TYPE_CODE_1] = 'Fdny Ems T' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK CRAN' OR
[VEHICLE_TYPE_CODE_1] = 'f15' OR
[VEHICLE_TYPE_CODE_1] = 'REVEL MOPE' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY INSUR' OR
[VEHICLE_TYPE_CODE_1] = 'Van (' OR
[VEHICLE_TYPE_CODE_1] = 'Barri' OR
[VEHICLE_TYPE_CODE_1] = 'none' OR
[VEHICLE_TYPE_CODE_1] = 'ROOD' OR
[VEHICLE_TYPE_CODE_1] = 'NYS A' OR
[VEHICLE_TYPE_CODE_1] = 'te' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY- Fire' OR
[VEHICLE_TYPE_CODE_1] = 'TRAILER CA' OR
[VEHICLE_TYPE_CODE_1] = 'NIU' OR
[VEHICLE_TYPE_CODE_1] = 'City vehic' OR
[VEHICLE_TYPE_CODE_1] = 'DEPT VAN #' OR
[VEHICLE_TYPE_CODE_1] = 'MARK' OR
[VEHICLE_TYPE_CODE_1] = 'hi-lo' OR
[VEHICLE_TYPE_CODE_1] = 'yellow cab' OR
[VEHICLE_TYPE_CODE_1] = 'nyu s' OR
[VEHICLE_TYPE_CODE_1] = 'SKID STEER' OR
[VEHICLE_TYPE_CODE_1] = 'Car carrie' OR
[VEHICLE_TYPE_CODE_1] = 'LOCOMOTIVE' OR
[VEHICLE_TYPE_CODE_1] = 'ENGINE SP0' OR
[VEHICLE_TYPE_CODE_1] = 'escavator' OR
[VEHICLE_TYPE_CODE_1] = 'CABIN' OR
[VEHICLE_TYPE_CODE_1] = 'Token' OR
[VEHICLE_TYPE_CODE_1] = '999' OR
[VEHICLE_TYPE_CODE_1] = 'Asphalt Pa' OR
[VEHICLE_TYPE_CODE_1] = 'SW/VAN' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY LADER' OR
[VEHICLE_TYPE_CODE_1] = 'LIT DIRECT' OR
[VEHICLE_TYPE_CODE_1] = 'DOT R' OR
[VEHICLE_TYPE_CODE_1] = 'Tram' OR
[VEHICLE_TYPE_CODE_1] = 'subar' OR
[VEHICLE_TYPE_CODE_1] = 'YW PO' OR
[VEHICLE_TYPE_CODE_1] = '?omme' OR
[VEHICLE_TYPE_CODE_1] = 'METRO TRAN' OR
[VEHICLE_TYPE_CODE_1] = 'T880' OR
[VEHICLE_TYPE_CODE_1] = 'ems b' OR
[VEHICLE_TYPE_CODE_1] = 'Lim' OR
[VEHICLE_TYPE_CODE_1] = 'MOBILITY S' OR
[VEHICLE_TYPE_CODE_1] = 'forlift' OR
[VEHICLE_TYPE_CODE_1] = 'CAT.' OR
[VEHICLE_TYPE_CODE_1] = 'DELV WH' OR
[VEHICLE_TYPE_CODE_1] = 'City Bus' OR
[VEHICLE_TYPE_CODE_1] = 'camper tra' OR
[VEHICLE_TYPE_CODE_1] = 'I-haul' OR
[VEHICLE_TYPE_CODE_1] = 'E450' OR
[VEHICLE_TYPE_CODE_1] = 'LCOM' OR
[VEHICLE_TYPE_CODE_1] = '4' OR
[VEHICLE_TYPE_CODE_1] = 'NYPD VAN' OR
[VEHICLE_TYPE_CODE_1] = 'Piggy back' OR
[VEHICLE_TYPE_CODE_1] = 'SHUTTLE BU' OR
[VEHICLE_TYPE_CODE_1] = 'Lawnmower' OR
[VEHICLE_TYPE_CODE_1] = 'kick scoot' OR
[VEHICLE_TYPE_CODE_1] = 'FUSION' OR
[VEHICLE_TYPE_CODE_1] = 'SWEEPER TR' OR
[VEHICLE_TYPE_CODE_1] = 'TR/KI' OR
[VEHICLE_TYPE_CODE_1] = 'MARKED RMP' OR
[VEHICLE_TYPE_CODE_1] = 'Nissan' OR
[VEHICLE_TYPE_CODE_1] = 'STACK' OR
[VEHICLE_TYPE_CODE_1] = 'PSP' OR
[VEHICLE_TYPE_CODE_1] = 'box van' OR
[VEHICLE_TYPE_CODE_1] = 'CAR/SUV' OR
[VEHICLE_TYPE_CODE_1] = '11-VA' OR
[VEHICLE_TYPE_CODE_1] = 'BOX CAR' OR
[VEHICLE_TYPE_CODE_1] = 'HUMVEE' OR
[VEHICLE_TYPE_CODE_1] = 'ASPHALT RO' OR
[VEHICLE_TYPE_CODE_1] = '1C' OR
[VEHICLE_TYPE_CODE_1] = 'LIEBH' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK COMM' OR
[VEHICLE_TYPE_CODE_1] = 'Tow-t' OR
[VEHICLE_TYPE_CODE_1] = 'SYBN' OR
[VEHICLE_TYPE_CODE_1] = 'R/V C' OR
[VEHICLE_TYPE_CODE_1] = '12 passage' OR
[VEHICLE_TYPE_CODE_1] = 'E3' OR
[VEHICLE_TYPE_CODE_1] = 'GAS POWERE' OR
[VEHICLE_TYPE_CODE_1] = 'AMUBULANCE' OR
[VEHICLE_TYPE_CODE_1] = 'POLIC' OR
[VEHICLE_TYPE_CODE_1] = 'LOADE' OR
[VEHICLE_TYPE_CODE_1] = '2 DR' OR
[VEHICLE_TYPE_CODE_1] = 'Collection' OR
[VEHICLE_TYPE_CODE_1] = 'PROMASTER' OR
[VEHICLE_TYPE_CODE_1] = 'FIRTRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'USPS2' OR
[VEHICLE_TYPE_CODE_1] = 'UTLIT' OR
[VEHICLE_TYPE_CODE_1] = 'U-Haul min' OR
[VEHICLE_TYPE_CODE_1] = 'MVP' OR
[VEHICLE_TYPE_CODE_1] = 'SCOMM' OR
[VEHICLE_TYPE_CODE_1] = 'U HAUL TRU' OR
[VEHICLE_TYPE_CODE_1] = 'CHART' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY mecha' OR
[VEHICLE_TYPE_CODE_1] = 'MILITARY' OR
[VEHICLE_TYPE_CODE_1] = 'CARRIER' OR
[VEHICLE_TYPE_CODE_1] = 'MANUAL SCO' OR
[VEHICLE_TYPE_CODE_1] = 'D2' OR
[VEHICLE_TYPE_CODE_1] = 'sanitaion' OR
[VEHICLE_TYPE_CODE_1] = 'TKTR' OR
[VEHICLE_TYPE_CODE_1] = 'passa' OR
[VEHICLE_TYPE_CODE_1] = 'omni' OR
[VEHICLE_TYPE_CODE_1] = 'depar' OR
[VEHICLE_TYPE_CODE_1] = 'LMTV' OR
[VEHICLE_TYPE_CODE_1] = 'COM T' OR
[VEHICLE_TYPE_CODE_1] = '10 Paaseng' OR
[VEHICLE_TYPE_CODE_1] = 'RIV 2022' OR
[VEHICLE_TYPE_CODE_1] = 'RINGO' OR
[VEHICLE_TYPE_CODE_1] = 'Isuzu' OR
[VEHICLE_TYPE_CODE_1] = 'M2' OR
[VEHICLE_TYPE_CODE_1] = 'COMER' OR
[VEHICLE_TYPE_CODE_1] = 'SD' OR
[VEHICLE_TYPE_CODE_1] = 'TRANSIT VA' OR
[VEHICLE_TYPE_CODE_1] = 'delviery' OR
[VEHICLE_TYPE_CODE_1] = 'SWEPE' OR
[VEHICLE_TYPE_CODE_1] = 'PEPSI DELI' OR
[VEHICLE_TYPE_CODE_1] = 'PEDAL BIKE' OR
[VEHICLE_TYPE_CODE_1] = 'BOX H' OR
[VEHICLE_TYPE_CODE_1] = 'DOT TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'EMS/VAN' OR
[VEHICLE_TYPE_CODE_1] = 'HI TA' OR
[VEHICLE_TYPE_CODE_1] = 'NO/BU' OR
[VEHICLE_TYPE_CODE_1] = 'HEAVY TRUC' OR
[VEHICLE_TYPE_CODE_1] = 'X TRL' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY 245 E' OR
[VEHICLE_TYPE_CODE_1] = 'del truck' OR
[VEHICLE_TYPE_CODE_1] = '3DOOR' OR
[VEHICLE_TYPE_CODE_1] = 'C 1' OR
[VEHICLE_TYPE_CODE_1] = 'U-HAUL TRU' OR
[VEHICLE_TYPE_CODE_1] = 'RV/VAN' OR
[VEHICLE_TYPE_CODE_1] = 'GRUMM' OR
[VEHICLE_TYPE_CODE_1] = 'VANG' OR
[VEHICLE_TYPE_CODE_1] = 'COMMM' OR
[VEHICLE_TYPE_CODE_1] = 'TL TR' OR
[VEHICLE_TYPE_CODE_1] = 'COLL' OR
[VEHICLE_TYPE_CODE_1] = 'Waste truc' OR
[VEHICLE_TYPE_CODE_1] = 'Mercedes' OR
[VEHICLE_TYPE_CODE_1] = '4whee' OR
[VEHICLE_TYPE_CODE_1] = 'R.M.P.' OR
[VEHICLE_TYPE_CODE_1] = 'BOAT' OR
[VEHICLE_TYPE_CODE_1] = 'MAC' OR
[VEHICLE_TYPE_CODE_1] = 'MDX' OR
[VEHICLE_TYPE_CODE_1] = 'Stake' OR
[VEHICLE_TYPE_CODE_1] = 'gas mo ped' OR
[VEHICLE_TYPE_CODE_1] = 'usps  van' OR
[VEHICLE_TYPE_CODE_1] = 'H1' OR
[VEHICLE_TYPE_CODE_1] = 'E REVEL SC' OR
[VEHICLE_TYPE_CODE_1] = 'BTM' OR
[VEHICLE_TYPE_CODE_1] = 'FORK-' OR
[VEHICLE_TYPE_CODE_1] = 'Traffic To' OR
[VEHICLE_TYPE_CODE_1] = 'seagr' OR
[VEHICLE_TYPE_CODE_1] = '315 e' OR
[VEHICLE_TYPE_CODE_1] = '4 RUN' OR
[VEHICLE_TYPE_CODE_1] = 'TRAC.' OR
[VEHICLE_TYPE_CODE_1] = 'Fd fi' OR
[VEHICLE_TYPE_CODE_1] = 'Yellow sch' OR
[VEHICLE_TYPE_CODE_1] = 'Dent and S' OR
[VEHICLE_TYPE_CODE_1] = 'TRAILER/FL' OR
[VEHICLE_TYPE_CODE_1] = 'U.S. POSTA' OR
[VEHICLE_TYPE_CODE_1] = 'US MA' OR
[VEHICLE_TYPE_CODE_1] = 'ELEC. UNIC' OR
[VEHICLE_TYPE_CODE_1] = 'TRLR PLT,' OR
[VEHICLE_TYPE_CODE_1] = 'g scl' OR
[VEHICLE_TYPE_CODE_1] = 'FRHT TRAIL' OR
[VEHICLE_TYPE_CODE_1] = 'BACK HOE' OR
[VEHICLE_TYPE_CODE_1] = 'BLOCK' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK FLAT' OR
[VEHICLE_TYPE_CODE_1] = '11111' OR
[VEHICLE_TYPE_CODE_1] = 'MOTORIZEDS' OR
[VEHICLE_TYPE_CODE_1] = 'VAGON' OR
[VEHICLE_TYPE_CODE_1] = 'Ford EC2' OR
[VEHICLE_TYPE_CODE_1] = 'OLC' OR
[VEHICLE_TYPE_CODE_1] = 'COACH' OR
[VEHICLE_TYPE_CODE_1] = 'frh' OR
[VEHICLE_TYPE_CODE_1] = 'E-SKATEBOA' OR
[VEHICLE_TYPE_CODE_1] = 'Pick wh' OR
[VEHICLE_TYPE_CODE_1] = 'dhl t' OR
[VEHICLE_TYPE_CODE_1] = 'COUPE' OR
[VEHICLE_TYPE_CODE_1] = 'CHEVR' OR
[VEHICLE_TYPE_CODE_1] = 'RV/Tr' OR
[VEHICLE_TYPE_CODE_1] = 'G Sem' OR
[VEHICLE_TYPE_CODE_1] = 'REN' OR
[VEHICLE_TYPE_CODE_1] = 'MOPED 150C' OR
[VEHICLE_TYPE_CODE_1] = 'com v' OR
[VEHICLE_TYPE_CODE_1] = 'TRUCK W/TR' OR
[VEHICLE_TYPE_CODE_1] = 'POSTAL VEH' OR
[VEHICLE_TYPE_CODE_1] = 'omm' OR
[VEHICLE_TYPE_CODE_1] = 'CHERV' OR
[VEHICLE_TYPE_CODE_1] = 'HD' OR
[VEHICLE_TYPE_CODE_1] = 'MOOPER' OR
[VEHICLE_TYPE_CODE_1] = 'prks' OR
[VEHICLE_TYPE_CODE_1] = 'BOXTRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'ARMOR' OR
[VEHICLE_TYPE_CODE_1] = 'NYFD ambul' OR
[VEHICLE_TYPE_CODE_1] = 'Pas (4dr s' OR
[VEHICLE_TYPE_CODE_1] = 'ECOM' OR
[VEHICLE_TYPE_CODE_1] = 'SEDONA' OR
[VEHICLE_TYPE_CODE_1] = 'FD LADDER' OR
[VEHICLE_TYPE_CODE_1] = '35 FT' OR
[VEHICLE_TYPE_CODE_1] = 'ME/BE' OR
[VEHICLE_TYPE_CODE_1] = 'US GO' OR
[VEHICLE_TYPE_CODE_1] = 'Ladder' OR
[VEHICLE_TYPE_CODE_1] = 'G1' OR
[VEHICLE_TYPE_CODE_1] = 'nyfd' OR
[VEHICLE_TYPE_CODE_1] = 'g spc' OR
[VEHICLE_TYPE_CODE_1] = 'Thomas' OR
[VEHICLE_TYPE_CODE_1] = 'Go kart' OR
[VEHICLE_TYPE_CODE_1] = 'range' OR
[VEHICLE_TYPE_CODE_1] = 'U-HAL' OR
[VEHICLE_TYPE_CODE_1] = '5' OR
[VEHICLE_TYPE_CODE_1] = 'UNKWOWN' OR
[VEHICLE_TYPE_CODE_1] = 'G1`' OR
[VEHICLE_TYPE_CODE_1] = 'fedx' OR
[VEHICLE_TYPE_CODE_1] = 'E- Bi' OR
[VEHICLE_TYPE_CODE_1] = 'SEA' OR
[VEHICLE_TYPE_CODE_1] = 'APORT' OR
[VEHICLE_TYPE_CODE_1] = 'PSR' OR
[VEHICLE_TYPE_CODE_1] = 'EMS -BUS' OR
[VEHICLE_TYPE_CODE_1] = 'GMC ECOM' OR
[VEHICLE_TYPE_CODE_1] = 'RMP V' OR
[VEHICLE_TYPE_CODE_1] = 'US MAIL #1' OR
[VEHICLE_TYPE_CODE_1] = 'EC3' OR
[VEHICLE_TYPE_CODE_1] = 'sanitaton' OR
[VEHICLE_TYPE_CODE_1] = 'ManPower s' OR
[VEHICLE_TYPE_CODE_1] = 'KUBOT' OR
[VEHICLE_TYPE_CODE_1] = 'STREET' OR
[VEHICLE_TYPE_CODE_1] = 'LTRL' OR
[VEHICLE_TYPE_CODE_1] = 'SERVI' OR
[VEHICLE_TYPE_CODE_1] = 'TRANSIT' OR
[VEHICLE_TYPE_CODE_1] = 'bobct' OR
[VEHICLE_TYPE_CODE_1] = 'PASS VAN' OR
[VEHICLE_TYPE_CODE_1] = 'MTA V' OR
[VEHICLE_TYPE_CODE_1] = 'C0MME' OR
[VEHICLE_TYPE_CODE_1] = 'SANMEN COU' OR
[VEHICLE_TYPE_CODE_1] = 'UHAL' OR
[VEHICLE_TYPE_CODE_1] = 'Penske Box' OR
[VEHICLE_TYPE_CODE_1] = 'E MOTORCYC' OR
[VEHICLE_TYPE_CODE_1] = 'f1' OR
[VEHICLE_TYPE_CODE_1] = 'SPARK150 S' OR
[VEHICLE_TYPE_CODE_1] = 'Ford FF' OR
[VEHICLE_TYPE_CODE_1] = 'Ford f150' OR
[VEHICLE_TYPE_CODE_1] = 'FORD F-150' OR
[VEHICLE_TYPE_CODE_1] = 'ATTECHMENT' OR
[VEHICLE_TYPE_CODE_1] = 'GARBAGE ST' OR
[VEHICLE_TYPE_CODE_1] = 'NYC BUS' OR
[VEHICLE_TYPE_CODE_1] = 'John' OR
[VEHICLE_TYPE_CODE_1] = 'VANET' OR
[VEHICLE_TYPE_CODE_1] = 'EMI- TRAIL' OR
[VEHICLE_TYPE_CODE_1] = 'Food Trail' OR
[VEHICLE_TYPE_CODE_1] = 'E Bike w p' OR
[VEHICLE_TYPE_CODE_1] = 'Utility.' OR
[VEHICLE_TYPE_CODE_1] = 'tr/tr' OR
[VEHICLE_TYPE_CODE_1] = '26 ft' OR
[VEHICLE_TYPE_CODE_1] = 'E-UNICYCLE' OR
[VEHICLE_TYPE_CODE_1] = 'Pro master' OR
[VEHICLE_TYPE_CODE_1] = 'Bread truc' OR
[VEHICLE_TYPE_CODE_1] = 'CMS-T' OR
[VEHICLE_TYPE_CODE_1] = 'ELEC.' OR
[VEHICLE_TYPE_CODE_1] = 'CAMPER VAN' OR
[VEHICLE_TYPE_CODE_1] = '3DC-' OR
[VEHICLE_TYPE_CODE_1] = 'Limousine' OR
[VEHICLE_TYPE_CODE_1] = 'SUDN' OR
[VEHICLE_TYPE_CODE_1] = 'utv bobcat' OR
[VEHICLE_TYPE_CODE_1] = 'SLINGSHOT' OR
[VEHICLE_TYPE_CODE_1] = 'towe truck' OR
[VEHICLE_TYPE_CODE_1] = 'SCL' OR
[VEHICLE_TYPE_CODE_1] = 'cross' OR
[VEHICLE_TYPE_CODE_1] = 'GE/SC' OR
[VEHICLE_TYPE_CODE_1] = 'PASS-' OR
[VEHICLE_TYPE_CODE_1] = '.' OR
[VEHICLE_TYPE_CODE_1] = 'UNK BOX TR' OR
[VEHICLE_TYPE_CODE_1] = 'FD TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'J1' OR
[VEHICLE_TYPE_CODE_1] = 'f-250' OR
[VEHICLE_TYPE_CODE_1] = '0' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY CHIEF' OR
[VEHICLE_TYPE_CODE_1] = 'TR-Trailer' OR
[VEHICLE_TYPE_CODE_1] = 'Mecha' OR
[VEHICLE_TYPE_CODE_1] = 'small' OR
[VEHICLE_TYPE_CODE_1] = 'FLED' OR
[VEHICLE_TYPE_CODE_1] = 'PUMPE' OR
[VEHICLE_TYPE_CODE_1] = '9999' OR
[VEHICLE_TYPE_CODE_1] = 'MTR H' OR
[VEHICLE_TYPE_CODE_1] = 'Yamaha' OR
[VEHICLE_TYPE_CODE_1] = 'TIR' OR
[VEHICLE_TYPE_CODE_1] = 'DEMA-' OR
[VEHICLE_TYPE_CODE_1] = 'A,n' OR
[VEHICLE_TYPE_CODE_1] = 'COMMERICIA' OR
[VEHICLE_TYPE_CODE_1] = 'NYPD Traff' OR
[VEHICLE_TYPE_CODE_1] = 'scooc' OR
[VEHICLE_TYPE_CODE_1] = 'UHUAL' OR
[VEHICLE_TYPE_CODE_1] = 'POSTO' OR
[VEHICLE_TYPE_CODE_1] = 'KP160' OR
[VEHICLE_TYPE_CODE_1] = 'CONTR' OR
[VEHICLE_TYPE_CODE_1] = 'REVEL scoo' OR
[VEHICLE_TYPE_CODE_1] = 'moter' OR
[VEHICLE_TYPE_CODE_1] = 'MOVING TRU' OR
[VEHICLE_TYPE_CODE_1] = 'USPS TRUC,' OR
[VEHICLE_TYPE_CODE_1] = 'e tow' OR
[VEHICLE_TYPE_CODE_1] = 'FORD AMBUL' OR
[VEHICLE_TYPE_CODE_1] = 'Flat bed t' OR
[VEHICLE_TYPE_CODE_1] = 'MINI VAHN' OR
[VEHICLE_TYPE_CODE_1] = '7' OR
[VEHICLE_TYPE_CODE_1] = 'G AMB' OR
[VEHICLE_TYPE_CODE_1] = 'USP M' OR
[VEHICLE_TYPE_CODE_1] = 'School van' OR
[VEHICLE_TYPE_CODE_1] = 'NYC M' OR
[VEHICLE_TYPE_CODE_1] = 'CHASSIS &' OR
[VEHICLE_TYPE_CODE_1] = 'e bike uni' OR
[VEHICLE_TYPE_CODE_1] = 'VAN/B' OR
[VEHICLE_TYPE_CODE_1] = 'LSA' OR
[VEHICLE_TYPE_CODE_1] = 'Kubota bac' OR
[VEHICLE_TYPE_CODE_1] = 'VERZION VA' OR
[VEHICLE_TYPE_CODE_1] = 'Ram Promas' OR
[VEHICLE_TYPE_CODE_1] = 'UNKN' OR
[VEHICLE_TYPE_CODE_1] = 'NYC a' OR
[VEHICLE_TYPE_CODE_1] = 'conta' OR
[VEHICLE_TYPE_CODE_1] = 'Grail' OR
[VEHICLE_TYPE_CODE_1] = 'Dept Tow t' OR
[VEHICLE_TYPE_CODE_1] = 'SEMI TRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'TAN P' OR
[VEHICLE_TYPE_CODE_1] = 'YALE' OR
[VEHICLE_TYPE_CODE_1] = 'UPS M' OR
[VEHICLE_TYPE_CODE_1] = 'POLICE VEH' OR
[VEHICLE_TYPE_CODE_1] = 'charter bu' OR
[VEHICLE_TYPE_CODE_1] = '''lime mope' OR
[VEHICLE_TYPE_CODE_1] = 'TTAILER' OR
[VEHICLE_TYPE_CODE_1] = 'GOLF CAR' OR
[VEHICLE_TYPE_CODE_1] = 'crane boom' OR
[VEHICLE_TYPE_CODE_1] = 'WORKH' OR
[VEHICLE_TYPE_CODE_1] = 'Farm Vehicle' OR
[VEHICLE_TYPE_CODE_1] = 'push' OR
[VEHICLE_TYPE_CODE_1] = 'Comix' OR
[VEHICLE_TYPE_CODE_1] = 'Yamah' OR
[VEHICLE_TYPE_CODE_1] = '250-3' OR
[VEHICLE_TYPE_CODE_1] = 'CUSHM' OR
[VEHICLE_TYPE_CODE_1] = 'ukn' OR
[VEHICLE_TYPE_CODE_1] = 'YELLOW BUS' OR
[VEHICLE_TYPE_CODE_1] = 'Usaa' OR
[VEHICLE_TYPE_CODE_1] = 'SMYELLSCHO' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY EMS#1' OR
[VEHICLE_TYPE_CODE_1] = 'atv p' OR
[VEHICLE_TYPE_CODE_1] = 'ELECTRIC C' OR
[VEHICLE_TYPE_CODE_1] = 'principle' OR
[VEHICLE_TYPE_CODE_1] = 'SMART CAR' OR
[VEHICLE_TYPE_CODE_1] = 'TRACK EXCA' OR
[VEHICLE_TYPE_CODE_1] = 'Lift' OR
[VEHICLE_TYPE_CODE_1] = 'USPS # 487' OR
[VEHICLE_TYPE_CODE_1] = 'Gas dirt b' OR
[VEHICLE_TYPE_CODE_1] = 'COT' OR
[VEHICLE_TYPE_CODE_1] = 'CMIXER' OR
[VEHICLE_TYPE_CODE_1] = 'BED T' OR
[VEHICLE_TYPE_CODE_1] = 'ELECTRIC B' OR
[VEHICLE_TYPE_CODE_1] = 'Wh Ford co' OR
[VEHICLE_TYPE_CODE_1] = 'Carriage' OR
[VEHICLE_TYPE_CODE_1] = 'GOVERMENT' OR
[VEHICLE_TYPE_CODE_1] = 'UTILITY VA' OR
[VEHICLE_TYPE_CODE_1] = 'ulili' OR
[VEHICLE_TYPE_CODE_1] = 'PS' OR
[VEHICLE_TYPE_CODE_1] = 'UPS' OR
[VEHICLE_TYPE_CODE_1] = 'TRAILOR' OR
[VEHICLE_TYPE_CODE_1] = 'RGR' OR
[VEHICLE_TYPE_CODE_1] = 'CRF Carria' OR
[VEHICLE_TYPE_CODE_1] = 'van c' OR
[VEHICLE_TYPE_CODE_1] = 'CHERR' OR
[VEHICLE_TYPE_CODE_1] = 'USPCS' OR
[VEHICLE_TYPE_CODE_1] = '2015' OR
[VEHICLE_TYPE_CODE_1] = 'P/SE' OR
[VEHICLE_TYPE_CODE_1] = 'semi-trail' OR
[VEHICLE_TYPE_CODE_1] = 'Postoffice' OR
[VEHICLE_TYPE_CODE_1] = 'TLR' OR
[VEHICLE_TYPE_CODE_1] = 'SANTI' OR
[VEHICLE_TYPE_CODE_1] = 'COMB' OR
[VEHICLE_TYPE_CODE_1] = 'DUMPTRUCK' OR
[VEHICLE_TYPE_CODE_1] = 'ORION' OR
[VEHICLE_TYPE_CODE_1] = 'Flatbed Pi' OR
[VEHICLE_TYPE_CODE_1] = 'SFI' OR
[VEHICLE_TYPE_CODE_1] = 'yy' OR
[VEHICLE_TYPE_CODE_1] = 'Small Bus' OR
[VEHICLE_TYPE_CODE_1] = 'DELV BR' OR
[VEHICLE_TYPE_CODE_1] = 'almbulance' OR
[VEHICLE_TYPE_CODE_1] = 'E ONE' OR
[VEHICLE_TYPE_CODE_1] = 'BLACK' OR
[VEHICLE_TYPE_CODE_1] = 'Ford Couri' OR
[VEHICLE_TYPE_CODE_1] = 'BUS (OMNIB' OR
[VEHICLE_TYPE_CODE_1] = 'LSV' OR
[VEHICLE_TYPE_CODE_1] = '985' OR
[VEHICLE_TYPE_CODE_1] = 'DEIV' OR
[VEHICLE_TYPE_CODE_1] = 'Toyota' OR
[VEHICLE_TYPE_CODE_1] = 'PET' OR
[VEHICLE_TYPE_CODE_1] = 'VAN E' OR
[VEHICLE_TYPE_CODE_1] = 'Pvt Ambula' OR
[VEHICLE_TYPE_CODE_1] = 'HERTZ RAM' OR
[VEHICLE_TYPE_CODE_1] = 'DOT EQUIPM' OR
[VEHICLE_TYPE_CODE_1] = 'rz' OR
[VEHICLE_TYPE_CODE_1] = 'Front-Load' OR
[VEHICLE_TYPE_CODE_1] = 'postal bus' OR
[VEHICLE_TYPE_CODE_1] = 'DELVI' OR
[VEHICLE_TYPE_CODE_1] = 'DOT T' OR
[VEHICLE_TYPE_CODE_1] = 'Snow' OR
[VEHICLE_TYPE_CODE_1] = 'Stand up s' OR
[VEHICLE_TYPE_CODE_1] = 'Military v' OR
[VEHICLE_TYPE_CODE_1] = 'HD To' OR
[VEHICLE_TYPE_CODE_1] = 'FREIGT VAN' OR
[VEHICLE_TYPE_CODE_1] = 'GOVT' OR
[VEHICLE_TYPE_CODE_1] = 'MTA truck' OR
[VEHICLE_TYPE_CODE_1] = 'PRIVA' OR
[VEHICLE_TYPE_CODE_1] = 'TC' OR
[VEHICLE_TYPE_CODE_1] = 'F650' OR
[VEHICLE_TYPE_CODE_1] = 'FR`' OR
[VEHICLE_TYPE_CODE_1] = 'OML/OMNIBU' OR
[VEHICLE_TYPE_CODE_1] = 'OZ MO' OR
[VEHICLE_TYPE_CODE_1] = 'SM YW' OR
[VEHICLE_TYPE_CODE_1] = 'AMBULANVE' OR
[VEHICLE_TYPE_CODE_1] = 'MTA Van' OR
[VEHICLE_TYPE_CODE_1] = 'FRT' OR
[VEHICLE_TYPE_CODE_1] = '12 PASSENG' OR
[VEHICLE_TYPE_CODE_1] = 'FLYWING MO' OR
[VEHICLE_TYPE_CODE_1] = 'delie' OR
[VEHICLE_TYPE_CODE_1] = 'AMBALANCE' OR
[VEHICLE_TYPE_CODE_1] = 'USPS small' OR
[VEHICLE_TYPE_CODE_1] = 'MTA U' OR
[VEHICLE_TYPE_CODE_1] = 'AERIA' OR
[VEHICLE_TYPE_CODE_1] = 'REG' OR
[VEHICLE_TYPE_CODE_1] = 'CHEVY EXPR' OR
[VEHICLE_TYPE_CODE_1] = '997' OR
[VEHICLE_TYPE_CODE_1] = 'CAB' OR
[VEHICLE_TYPE_CODE_1] = 'SUBN/Van' OR
[VEHICLE_TYPE_CODE_1] = 'Mo pa' OR
[VEHICLE_TYPE_CODE_1] = 'OMT/T' OR
[VEHICLE_TYPE_CODE_1] = 'police rep' OR
[VEHICLE_TYPE_CODE_1] = 'FedEx box' OR
[VEHICLE_TYPE_CODE_1] = 'SKID LOADE' OR
[VEHICLE_TYPE_CODE_1] = 'MARKED VAN' OR
[VEHICLE_TYPE_CODE_1] = 'LCOMM' OR
[VEHICLE_TYPE_CODE_1] = 'D/V WB' OR
[VEHICLE_TYPE_CODE_1] = 'rmb' OR
[VEHICLE_TYPE_CODE_1] = 'usps 88716' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY EMT' OR
[VEHICLE_TYPE_CODE_1] = 'FREIG DELV' OR
[VEHICLE_TYPE_CODE_1] = 'dilevery t' OR
[VEHICLE_TYPE_CODE_1] = 'NYC FD' OR
[VEHICLE_TYPE_CODE_1] = 'COMMU' OR
[VEHICLE_TYPE_CODE_1] = 'cp' OR
[VEHICLE_TYPE_CODE_1] = 'US Mail Tr' OR
[VEHICLE_TYPE_CODE_1] = 'FLAT  BED' OR
[VEHICLE_TYPE_CODE_1] = 'backhoe re' OR
[VEHICLE_TYPE_CODE_1] = 'Feder' OR
[VEHICLE_TYPE_CODE_1] = 'PAS V' OR
[VEHICLE_TYPE_CODE_1] = 'progr' OR
[VEHICLE_TYPE_CODE_1] = 'Unknown ve' OR
[VEHICLE_TYPE_CODE_1] = 'COM DELIVE' OR
[VEHICLE_TYPE_CODE_1] = 'del' OR
[VEHICLE_TYPE_CODE_1] = 'NJ transit' OR
[VEHICLE_TYPE_CODE_1] = 'refuse tru' OR
[VEHICLE_TYPE_CODE_1] = 'pay loader' OR
[VEHICLE_TYPE_CODE_1] = 'conti' OR
[VEHICLE_TYPE_CODE_1] = 'VAN WH' OR
[VEHICLE_TYPE_CODE_1] = 'TCM' OR
[VEHICLE_TYPE_CODE_1] = 'Garbage' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY #226' OR
[VEHICLE_TYPE_CODE_1] = 'CONT' OR
[VEHICLE_TYPE_CODE_1] = 'TAILG' OR
[VEHICLE_TYPE_CODE_1] = 'UNKOWN' OR
[VEHICLE_TYPE_CODE_1] = 'CON E' OR
[VEHICLE_TYPE_CODE_1] = 'SAVANA' OR
[VEHICLE_TYPE_CODE_1] = 'HIGHL' OR
[VEHICLE_TYPE_CODE_1] = 'P/U' OR
[VEHICLE_TYPE_CODE_1] = '2 WHE' OR
[VEHICLE_TYPE_CODE_1] = 'TLC P' OR
[VEHICLE_TYPE_CODE_1] = 'CAMP' OR
[VEHICLE_TYPE_CODE_1] = 'high' OR
[VEHICLE_TYPE_CODE_1] = 'BULLDOZER' OR
[VEHICLE_TYPE_CODE_1] = 'message si' OR
[VEHICLE_TYPE_CODE_1] = 'White ambu' OR
[VEHICLE_TYPE_CODE_1] = 'ROADS' OR
[VEHICLE_TYPE_CODE_1] = 'dark color' OR
[VEHICLE_TYPE_CODE_1] = 'WORKM' OR
[VEHICLE_TYPE_CODE_1] = '2000' OR
[VEHICLE_TYPE_CODE_1] = '100th truc' OR
[VEHICLE_TYPE_CODE_1] = 'Truck/bus' OR
[VEHICLE_TYPE_CODE_1] = 'WINEB' OR
[VEHICLE_TYPE_CODE_1] = 'CHEVROLET' OR
[VEHICLE_TYPE_CODE_1] = 'MO PE' OR
[VEHICLE_TYPE_CODE_1] = 'SURET' OR
[VEHICLE_TYPE_CODE_1] = '50cc mini' OR
[VEHICLE_TYPE_CODE_1] = 'Ele. Unicy' OR
[VEHICLE_TYPE_CODE_1] = 'Parce' OR
[VEHICLE_TYPE_CODE_1] = 'MCY B' OR
[VEHICLE_TYPE_CODE_1] = 'HDC' OR
[VEHICLE_TYPE_CODE_1] = 'DOT VEHICL' OR
[VEHICLE_TYPE_CODE_1] = 'FDNY UTILI' OR
[VEHICLE_TYPE_CODE_1] = '13'
	) as TempTable

--Replace faulty vehicle codes in TempTable with new ones
UPDATE ##TempTable
SET ##TempTable.VEHICLE_TYPE_CODE_1 = CASE ##TempTable.VEHICLE_TYPE_CODE_1
WHEN 'Station Wagon/Sport Utility Vehicle' THEN 'SUV'
WHEN 'PASSENGER VEHICLE' THEN 'Unidentified Passenger Vehicle'
WHEN 'SPORT UTILITY / STATION WAGON' THEN 'SUV'
WHEN 'Pick-up Truck' THEN 'Pickup Truck'
WHEN '4 dr sedan' THEN 'Sedan'
WHEN 'OTHER' THEN Null
WHEN 'UNKNOWN' THEN Null
WHEN 'Bike' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'LARGE COM VEH(6 OR MORE TIRES)' THEN 'Unidentified Commercial Vehicles'
WHEN 'SMALL COM VEH(4 TIRES) ' THEN 'Unidentified Commercial Vehicles'
WHEN 'Tractor Truck Diesel' THEN 'Construction'
WHEN 'LIVERY VEHICLE' THEN 'Livery'
WHEN 'Dump' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'E-Bike' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN '2 dr sedan' THEN 'Sedan'
WHEN 'PK' THEN 'Pickup Truck'
WHEN 'Flat Bed' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'E-Scooter' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Moped' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Garbage or Refuse' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'Carry All' THEN 'Carryall, Golf Carts & Similar'
WHEN 'Tractor Truck Gasoline' THEN 'Construction'
WHEN 'Tow Truck / Wrecker' THEN 'Tow Trucks'
WHEN 'FIRE TRUCK' THEN 'Fire Department Vehicles'
WHEN 'Chassis Cab' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'Tanker' THEN 'Large Cargo Vehicles'
WHEN 'Motorscooter' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'BICYCLE' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'Ambul' THEN 'Ambulance'
WHEN 'Motorbike' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Concrete Mixer' THEN 'Construction'
WHEN 'Refrigerated Van' THEN 'Refrigeration Trasport'
WHEN 'Flat Rack' THEN 'Large Cargo Vehicles'
WHEN '3-Door' THEN 'Sedan'
WHEN 'scooter' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'LIMO' THEN 'Limousine'
WHEN 'TRUCK' THEN 'Unidentified Passenger Vehicle'
WHEN 'Beverage Truck' THEN 'Food & Beverage'
WHEN 'TRAIL' THEN 'Trailers'
WHEN 'SCHOOL BUS' THEN 'Schoolbus'
WHEN 'FIRE' THEN 'Fire Department Vehicles'
WHEN 'Lift Boom' THEN 'Construction'
WHEN 'Stake or Rack' THEN 'Construction'
WHEN 'FDNY' THEN 'Fire Department Vehicles'
WHEN 'subn' THEN 'Unidentified Passenger Vehicle'
WHEN 'Trailer' THEN 'Trailers'
WHEN 'Multi-Wheeled Vehicle' THEN 'Unidentified Commercial Vehicles'
WHEN 'TRACT' THEN 'Construction'
WHEN 'Snow Plow' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'E-Sco' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'AMBU' THEN 'Ambulance'
WHEN 'E-Bik' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Pedicab' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'TOW TRUCK' THEN 'Tow Trucks'
WHEN 'UNKNO' THEN Null
WHEN 'SCHOO' THEN 'Schoolbus'
WHEN 'COM' THEN 'Unidentified Commercial Vehicles'
WHEN 'Open Body' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'DELIV' THEN 'Delivery'
WHEN 'COMME' THEN 'Unidentified Commercial Vehicles'
WHEN 'Tow t' THEN 'Tow Trucks'
WHEN 'Bulk Agriculture' THEN 'Agriculture'
WHEN 'UNK' THEN Null
WHEN 'Firetruck' THEN 'Fire Department Vehicles'
WHEN 'BOX T' THEN 'Box Truck'
WHEN 'UTILI' THEN Null
WHEN 'SCOOT' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'DELV' THEN 'Delivery'
WHEN 'FIRET' THEN 'Fire Department Vehicles'
WHEN 'Pickup with mounted Camper' THEN 'Pickup Truck'
WHEN 'COMMERCIAL' THEN 'Unidentified Commercial Vehicles'
WHEN 'FDNY Ambul' THEN 'Fire Department Vehicles'
WHEN 'AMB' THEN 'Ambulance'
WHEN 'FORKL' THEN 'Construction'
WHEN 'Pallet' THEN 'Large Cargo Vehicles'
WHEN 'ELECT' THEN Null
WHEN 'pas' THEN 'Unidentified Passenger Vehicle'
WHEN 'UTIL' THEN Null
WHEN 'Lunch Wagon' THEN 'Food & Beverage'
WHEN 'PICK UP' THEN 'Pickup Truck'
WHEN 'pick' THEN 'Pickup Truck'
WHEN 'Minibike' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'FDNY TRUCK' THEN 'Fire Department Vehicles'
WHEN 'GARBA' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'FDNY FIRE' THEN 'Fire Department Vehicles'
WHEN 'STREE' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'FORD' THEN Null
WHEN 'Van Camper' THEN 'Van'
WHEN 'posta' THEN 'USPS'
WHEN 'Motorized Home' THEN 'Motor Home'
WHEN 'motor' THEN Null
WHEN 'GARBAGE TR' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'FLAT' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'TANK' THEN 'Large Cargo Vehicles'
WHEN 'Self' THEN Null
WHEN 'Minicycle' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'RV' THEN 'Motor Home'
WHEN 'WAGON' THEN Null
WHEN 'SANIT' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'picku' THEN 'Pickup Truck'
WHEN 'Hopper' THEN 'Train'
WHEN 'dump truck' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'Pick up tr' THEN 'Pickup Truck'
WHEN 'FREIG' THEN 'Large Cargo Vehicles'
WHEN 'TRL' THEN Null
WHEN 'FORKLIFT' THEN 'Construction'
WHEN 'MTA BUS' THEN 'Construction'
WHEN 'TRAC' THEN 'Construction'
WHEN 'TRK' THEN Null
WHEN 'PICKUP' THEN 'Pickup Truck'
WHEN 'FORK' THEN 'Construction'
WHEN 'UTILITY' THEN Null
WHEN 'Tow' THEN 'Tow Trucks'
WHEN 'MACK' THEN 'Large Cargo Vehicles'
WHEN 'REFG' THEN 'Refrigeration Trasport'
WHEN 'Sprinter V' THEN 'Unidentified Commercial Vehicles'
WHEN 'backh' THEN 'Construction'
WHEN 'Fork lift' THEN 'Construction'
WHEN 'USPS truck' THEN 'USPS'
WHEN 'US PO' THEN 'USPS'
WHEN 'SUV' THEN 'SUV'
WHEN 'GOLF CART' THEN 'Carryall, Golf Carts & Similar'
WHEN 'ROAD SWEEP' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'C1' THEN Null
WHEN 'Sanitation' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'passenger' THEN 'Unidentified Passenger Vehicle'
WHEN 'Vanette' THEN 'Van'
WHEN 'van t' THEN 'Van'
WHEN 'OMR' THEN Null
WHEN 'MTA B' THEN 'Construction'
WHEN 'VAN TRUCK' THEN 'Van'
WHEN 'Mail' THEN 'USPS'
WHEN 'SEMI' THEN 'Large Cargo Vehicles'
WHEN 'POWER' THEN Null
WHEN 'Golf' THEN 'Carryall, Golf Carts & Similar'
WHEN 'FIRE ENGIN' THEN 'Fire Department Vehicles'
WHEN 'PSD' THEN Null
WHEN 'MOTOR SCOO' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'DELIVERY T' THEN 'Delivery'
WHEN 'crane' THEN 'Construction'
WHEN 'road' THEN Null
WHEN 'SELF INSUR' THEN Null
WHEN 'OMT' THEN Null
WHEN 'Tractor Tr' THEN 'Construction'
WHEN 'Const' THEN 'Construction'
WHEN 'Glass Rack' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'Livestock Rack' THEN 'Agriculture'
WHEN 'FLATB' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'Pickup tru' THEN 'Pickup Truck'
WHEN 'Well Driller' THEN 'Construction'
WHEN 'ELECTRIC S' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'STAK' THEN Null
WHEN 'PC' THEN Null
WHEN 'N/A' THEN Null
WHEN 'SPC' THEN Null
WHEN 'COMM' THEN 'Unidentified Commercial Vehicles'
WHEN 'UHAUL' THEN 'Box Truck'
WHEN 'P/SH' THEN Null
WHEN 'STREET SWE' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'CEMEN' THEN 'Construction'
WHEN 'UTILITY VE' THEN Null
WHEN 'Delivery' THEN 'Delivery'
WHEN 'SPRIN' THEN 'Small Cargo Vehicles'
WHEN 'TRACTOR' THEN 'Construction'
WHEN 'tk' THEN Null
WHEN 'MAIL TRUCK' THEN 'USPS'
WHEN 'Power shov' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'F550' THEN Null
WHEN 'OML' THEN Null
WHEN 'Log' THEN Null
WHEN 'Food' THEN 'Food & Beverage Service'
WHEN 'PICK-' THEN 'Pickup Truck'
WHEN 'utility tr' THEN Null
WHEN 'CITY' THEN Null
WHEN 'YELLO' THEN Null
WHEN 'gas scoote' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Cargo' THEN Null
WHEN 'WHITE' THEN Null
WHEN 'Enclosed Body - Nonremovable Enclosure' THEN Null
WHEN 'government' THEN 'Unidentified Commercial Vehicles'
WHEN 'AMBULETTE' THEN 'Ambulance'
WHEN 'MTA' THEN Null
WHEN 'rmp' THEN Null
WHEN 'FDNY EMS' THEN 'Fire Department Vehicles'
WHEN 'MINI' THEN Null
WHEN 'PASSE' THEN 'Unidentified Passenger Vehicle'
WHEN 'NYPD' THEN 'Police'
WHEN 'SUBURBAN' THEN 'Unidentified Passenger Vehicle'
WHEN 'Pass' THEN 'Unidentified Passenger Vehicle'
WHEN 'US POSTAL' THEN 'USPS'
WHEN 'NYS Ambula' THEN 'Ambulance'
WHEN 'OMNIB' THEN 'Bus'
WHEN 'Postal tru' THEN 'USPS'
WHEN 'Horse' THEN 'Horse'
WHEN 'BOBCA' THEN 'Construction'
WHEN 'E bik' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'TRLR' THEN 'Trailers'
WHEN 'EMS' THEN 'Ambulance'
WHEN 'work' THEN Null
WHEN 'tr' THEN Null
WHEN 'Dirt Bike' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Enclosed Body - Removable Enclosure' THEN 'Small Cargo Vehicles'
WHEN 'GAS MOPED' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'ebike' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'SKATEBOARD' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'BOX' THEN 'Box Truck'
WHEN 'acces' THEN Null
WHEN 'FLATBED' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'FDNY Firet' THEN 'Fire Department Vehicles'
WHEN 'HINO' THEN Null
WHEN 'Cargo van' THEN 'Small Cargo Vehicles'
WHEN 'G COM' THEN Null
WHEN 'COURIER' THEN Null
WHEN 'FDNY LADDE' THEN 'Fire Department Vehicles'
WHEN 'FDNY ENGIN' THEN 'Fire Department Vehicles'
WHEN 'SUBUR' THEN 'Unidentified Passenger Vehicle'
WHEN 'Mopd' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'DELIVERY V' THEN 'Delivery'
WHEN 'FORD VAN' THEN 'Van'
WHEN 'Excavator' THEN 'Construction'
WHEN 'REFRI' THEN 'Refrigeration Trasport'
WHEN 'AMBULENCE' THEN 'Ambulance'
WHEN 'WORK VAN' THEN 'Livery'
WHEN 'CO' THEN Null
WHEN 'PICK-UP TR' THEN 'Pickup Truck'
WHEN 'Cement tru' THEN 'Construction'
WHEN 'USPS MAIL' THEN 'USPS'
WHEN 'mc' THEN Null
WHEN 'mcy' THEN Null
WHEN 'movin' THEN Null
WHEN 'JEEP' THEN 'SUV'
WHEN 'BULLD' THEN 'Construction'
WHEN 'Pick-Up' THEN 'Pickup Truck'
WHEN 'ICE C' THEN 'Ice Cream Truck'
WHEN 'Motorscoot' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'E scooter' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'CMIX' THEN 'Construction'
WHEN 'UT' THEN Null
WHEN 'Fedex' THEN 'Small Cargo Vehicles'
WHEN 'excav' THEN 'Construction'
WHEN 'TRANS' THEN Null
WHEN 'MACK TRUCK' THEN 'Large Cargo Vehicles'
WHEN 'U-Hau' THEN 'Box Truck'
WHEN 'unkow' THEN Null
WHEN 'Inter' THEN Null
WHEN 'C3' THEN Null
WHEN 'freight' THEN 'Large Cargo Vehicles'
WHEN 'FREIGHTLIN' THEN 'Large Cargo Vehicles'
WHEN 'SWEEP' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'Rescu' THEN Null
WHEN 'COURI' THEN Null
WHEN 'back' THEN Null
WHEN 'EMS bus' THEN 'Ambulance'
WHEN 'rd/s' THEN Null
WHEN 'VAN/T' THEN Null
WHEN 'LIGHT' THEN Null
WHEN 'REP' THEN Null
WHEN 'TANKE' THEN 'Large Cargo Vehicles'
WHEN 'CATER' THEN 'Food & Beverage Service'
WHEN 'TOWER' THEN Null
WHEN 'FORD TRANS' THEN Null
WHEN 'gator' THEN 'Construction'
WHEN 'BOBCAT' THEN 'Construction'
WHEN 'DIRT' THEN Null
WHEN 'LIVER' THEN 'Livery'
WHEN 'LADDER TRU' THEN 'Fire Department Vehicles'
WHEN 'UPS T' THEN 'Small Cargo Vehicles'
WHEN 'GOVER' THEN Null
WHEN 'WINNE' THEN Null
WHEN 'UPS TRUCK' THEN 'Small Cargo Vehicles'
WHEN 'MOBIL' THEN Null
WHEN 'A' THEN Null
WHEN 'EMS TRUCK' THEN 'Ambulance'
WHEN 'RENTA' THEN Null
WHEN 'Trc' THEN Null
WHEN 'Horse trai' THEN 'Horse'
WHEN 'TLC' THEN Null
WHEN 'Veriz' THEN Null
WHEN 'NYC SANITA' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'TRACK' THEN Null
WHEN 'skate' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'FIRE APPAR' THEN 'Fire Department Vehicles'
WHEN 'R/V' THEN 'Motor Home'
WHEN 'TL' THEN Null
WHEN 'Dodge' THEN Null
WHEN 'FOOD TRUCK' THEN 'Food & Beverage Service'
WHEN 'HRSE' THEN 'Horse'
WHEN 'D3' THEN Null
WHEN 'Grain' THEN 'Agriculture'
WHEN 'SCOM' THEN Null
WHEN 'SS' THEN Null
WHEN 'UTV' THEN Null
WHEN 'MOPAD' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'CASE' THEN Null
WHEN 'SE' THEN Null
WHEN '4D' THEN 'Sedan'
WHEN 'fd tr' THEN 'Fire Department Vehicles'
WHEN 'BOOM LIFT' THEN 'Construction'
WHEN 'Marke' THEN Null
WHEN 'CHEVY' THEN Null
WHEN 'L1' THEN Null
WHEN 'house on w' THEN 'Motor Home'
WHEN 'APPOR' THEN Null
WHEN 'spec' THEN Null
WHEN 'PKUP' THEN 'Pickup Truck'
WHEN 'PASSANGER' THEN 'Unidentified Passenger Vehicle'
WHEN 'MOTOR HOME' THEN 'Motor Home'
WHEN 'U-Haul' THEN 'Box Truck'
WHEN 'ECONOLINE' THEN Null
WHEN '4DS' THEN 'Sedan'
WHEN 'USPS POSTA' THEN 'USPS'
WHEN '3 WHE' THEN 'Sedan'
WHEN 'LIMOU' THEN 'Limousine'
WHEN 'FRIEG' THEN 'Large Cargo Vehicles'
WHEN 'VMS' THEN Null
WHEN '1' THEN Null
WHEN '4dsd' THEN 'Sedan'
WHEN '15 Pa' THEN 'Bus'
WHEN 'Mini Van' THEN 'Van'
WHEN 'ECONO' THEN Null
WHEN 'Backhoe' THEN 'Construction'
WHEN 'FRHT' THEN Null
WHEN 'NISSA' THEN Null
WHEN 'AMBULACE' THEN 'Ambulance'
WHEN 'PAYLO' THEN Null
WHEN 'Motorized' THEN Null
WHEN 'SEMI-' THEN 'Large Cargo Vehicles'
WHEN 'commerical' THEN 'Unidentified Commercial Vehicles'
WHEN 'dumps' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'FED E' THEN 'Small Cargo Vehicles'
WHEN 'MINIV' THEN 'Van'
WHEN 'OIL T' THEN 'Large Cargo Vehicles'
WHEN 'Electric m' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'St' THEN Null
WHEN 'GEICO' THEN Null
WHEN 'AMBULANE' THEN 'Ambulance'
WHEN 'CON ED TRU' THEN Null
WHEN 'SW' THEN Null
WHEN 'C2' THEN Null
WHEN 'FLEET' THEN Null
WHEN 'Post offic' THEN 'USPS'
WHEN 'NYCHA' THEN Null
WHEN 'BoxTr' THEN 'Box Truck'
WHEN 'e com' THEN Null
WHEN 'TF' THEN Null
WHEN 'BUCKE' THEN Null
WHEN 'Postal ser' THEN 'USPS'
WHEN 'MTA transi' THEN Null
WHEN 'DOLLY' THEN Null
WHEN 'HEAVY' THEN Null
WHEN 'NYPD TOW T' THEN 'Police'
WHEN 'Pavin' THEN Null
WHEN 'NYC AMBULA' THEN 'Ambulance'
WHEN 'PUMP' THEN Null
WHEN 'TOWTR' THEN 'Tow Trucks'
WHEN 'NOT I' THEN Null
WHEN 'Grumman LL' THEN Null
WHEN 'SMART' THEN Null
WHEN '50cc Scoot' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'STREET CLE' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'FRONT' THEN Null
WHEN 'FUEL' THEN Null
WHEN 'RGS' THEN Null
WHEN 'SCOO' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Access-A-R' THEN Null
WHEN 'DODGE RAM' THEN Null
WHEN 'amazon tru' THEN 'Small Cargo Vehicles'
WHEN 'Wheel' THEN Null
WHEN 'truck trai' THEN Null
WHEN 'I1' THEN Null
WHEN 'CART' THEN Null
WHEN 'ESU T' THEN Null
WHEN '4door' THEN 'Sedan'
WHEN 'Bicyc' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'FOOD CART' THEN 'Food & Beverage Service'
WHEN 'FD Ambulan' THEN 'Fire Department Vehicles'
WHEN 'PEDIC' THEN Null
WHEN 'SWT' THEN Null
WHEN 'BS' THEN Null
WHEN 'Omnibus' THEN 'Bus'
WHEN 'Ram' THEN Null
WHEN 'Budge' THEN Null
WHEN 'Dot' THEN Null
WHEN 'd1' THEN Null
WHEN 'Mopped' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Schoolbus' THEN 'Schoolbus'
WHEN 'SEGWA' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'NEW Y' THEN Null
WHEN 'Constructi' THEN 'Construction'
WHEN 'E bike' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'PSH' THEN Null
WHEN '3-whe' THEN Null
WHEN 'City Owned' THEN Null
WHEN 'NAVIG' THEN Null
WHEN 'Skywatch' THEN Null
WHEN 'SUB' THEN Null
WHEN 'na' THEN Null
WHEN 'USPS VAN' THEN 'USPS'
WHEN 'DUMPT' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'Subr' THEN Null
WHEN 'plow' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'VAV' THEN Null
WHEN 'NYC F' THEN 'Fire Department Vehicles'
WHEN 'US' THEN Null
WHEN 'fed ex tru' THEN 'Small Cargo Vehicles'
WHEN 'NYC FIRE T' THEN 'Fire Department Vehicles'
WHEN 'FREIGHT TR' THEN Null
WHEN 'toyot' THEN Null
WHEN 'SCOOTER GA' THEN Null
WHEN 'PERM' THEN Null
WHEN 'Van (Trans' THEN Null
WHEN 'NYC' THEN Null
WHEN 'TCN' THEN Null
WHEN 'KENWO' THEN Null
WHEN 'ladde' THEN Null
WHEN 'USPS VEHIC' THEN 'USPS'
WHEN 'APP' THEN Null
WHEN 'vespa' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'FLATBED TO' THEN 'Tow Trucks'
WHEN 'standing s' THEN Null
WHEN '12 Pa' THEN Null
WHEN 'BOOM' THEN Null
WHEN 'VAN W' THEN Null
WHEN 'Mailtruck' THEN 'USPS'
WHEN 'Horse carr' THEN 'Horse'
WHEN 'NYC TRANSI' THEN Null
WHEN 'LEFT' THEN Null
WHEN 'G TOW' THEN Null
WHEN 'Detached t' THEN 'Trailers'
WHEN 'EMS A' THEN Null
WHEN 'VAN/TRUCK' THEN Null
WHEN 'NYC D' THEN Null
WHEN 'Can' THEN Null
WHEN 'Bucket Tru' THEN 'Construction'
WHEN 'EMT Ambula' THEN 'Ambulance'
WHEN 'GLBEN' THEN Null
WHEN 'VPG' THEN Null
WHEN 'FLAT/' THEN Null
WHEN 'EMS T' THEN Null
WHEN 'USPOS' THEN 'USPS'
WHEN 'sterl' THEN Null
WHEN 'ABULANCE' THEN 'Ambulance'
WHEN '4DR' THEN Null
WHEN 'SPRINTER' THEN Null
WHEN 'SEMI TRAIL' THEN Null
WHEN 'work truck' THEN Null
WHEN 'E SCO' THEN Null
WHEN 'E AMB' THEN 'Ambulance'
WHEN 'PUMPER' THEN Null
WHEN 'Ice Cream' THEN 'Ice Cream Truck'
WHEN '18 WHEELER' THEN 'Large Cargo Vehicles'
WHEN 'LMB' THEN Null
WHEN 'FDNY EMS V' THEN 'Fire Department Vehicles'
WHEN 'OMS' THEN Null
WHEN 'BK' THEN Null
WHEN 'EMS Ambula' THEN 'Ambulance'
WHEN 'U HAU' THEN 'Box Truck'
WHEN 'ENGIN' THEN Null
WHEN 'CITY OF NE' THEN Null
WHEN 'SP PURPOSE' THEN Null
WHEN 'MINI BUS' THEN 'Bus'
WHEN 'concr' THEN 'Construction'
WHEN 'LTR' THEN Null
WHEN 'DIRTB' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'LIGHT TRAI' THEN Null
WHEN 'amulance' THEN 'Ambulance'
WHEN 'house' THEN Null
WHEN 'GRAY' THEN Null
WHEN 'G PSD' THEN Null
WHEN 'CHEV' THEN Null
WHEN 'FORD SPRIN' THEN Null
WHEN 'SUBN - AMB' THEN Null
WHEN 'TRT' THEN Null
WHEN 'carri' THEN Null
WHEN '5X8 T' THEN Null
WHEN 'Postal Box' THEN 'USPS'
WHEN 'RUBBE' THEN Null
WHEN 'Car C' THEN Null
WHEN 'LADDER CO' THEN Null
WHEN 'postal van' THEN 'USPS'
WHEN '2 DOO' THEN 'Sedan'
WHEN '�MBU' THEN 'Ambulance'
WHEN 'Razor Scoo' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'DIESE' THEN Null
WHEN 'NonMotordS' THEN Null
WHEN 'Bucketload' THEN Null
WHEN 'Shove' THEN Null
WHEN 'NYC FDNY #' THEN 'Fire Department Vehicles'
WHEN 'COM TRANS' THEN Null
WHEN 'ARMY' THEN Null
WHEN 'Cat 9' THEN Null
WHEN 'TRALI' THEN Null
WHEN 'Red moped' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'GREEN' THEN Null
WHEN 'ELE MOTORC' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'F550 ESU R' THEN Null
WHEN 'E - B' THEN Null
WHEN 'BOBCAT FOR' THEN 'Construction'
WHEN 'FEIG' THEN Null
WHEN 'NYNJ RAIL' THEN Null
WHEN 'MOTOR SKAT' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'SUBN WHI' THEN Null
WHEN 'Farm' THEN Null
WHEN 'SONATA' THEN Null
WHEN '994' THEN Null
WHEN 'Gator 4x4' THEN Null
WHEN 'Fire Truvk' THEN 'Fire Department Vehicles'
WHEN 'Yale Fork' THEN Null
WHEN 'red t' THEN Null
WHEN 'dp' THEN Null
WHEN 'nyc EMS' THEN Null
WHEN 'JOHN DEERE' THEN 'Agriculture'
WHEN 'Lime Scoot' THEN Null
WHEN 'REPAI' THEN Null
WHEN 'YW SCHOOL' THEN Null
WHEN 'Attac' THEN Null
WHEN 'CAT P' THEN Null
WHEN 'OTH' THEN Null
WHEN 'Hearse' THEN Null
WHEN 'DUMPSTER T' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'TRAILEE' THEN 'Trailers'
WHEN 'Leased amb' THEN Null
WHEN 'POWER LADD' THEN 'Construction'
WHEN 'ST150' THEN Null
WHEN '1S' THEN Null
WHEN 'EAMB' THEN Null
WHEN 'TTRAILER' THEN 'Trailers'
WHEN 'MTA C' THEN 'Construction'
WHEN 'E.M.S' THEN 'Ambulance'
WHEN 'USPS #7530' THEN 'USPS'
WHEN 'E-MOT' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'amdu' THEN 'Ambulance'
WHEN 'P PSD' THEN Null
WHEN 'MO-PED' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'AMBUKANCE' THEN 'Ambulance'
WHEN 'REFR' THEN 'Refrigeration Trasport'
WHEN 'SELF-' THEN Null
WHEN 'MOVING VAN' THEN 'Van'
WHEN 'PETIT CAB' THEN Null
WHEN 'Honda HRV' THEN 'SUV'
WHEN 'ford econo' THEN Null
WHEN 'comm.' THEN 'Unidentified Commercial Vehicles'
WHEN 'VA' THEN Null
WHEN 'ESU RESCUE' THEN Null
WHEN 'STATE' THEN Null
WHEN 'VAN A' THEN Null
WHEN 'Livery Bus' THEN 'Livery'
WHEN '3 doo' THEN Null
WHEN 'FRE' THEN Null
WHEN 'leu' THEN Null
WHEN 'EMS FDNY B' THEN 'Fire Department Vehicles'
WHEN 'GOLFCART' THEN Null
WHEN 'Quality tr' THEN Null
WHEN 'RAZOR150 M' THEN Null
WHEN 'nycta' THEN Null
WHEN 'dsny' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'DRILL RIG' THEN 'Construction'
WHEN 'REF BOX TR' THEN Null
WHEN 'X Amb' THEN 'Ambulance'
WHEN 'FREIGHT VA' THEN Null
WHEN 'NYCHA Van' THEN Null
WHEN 'MECHANICAL' THEN Null
WHEN 'EMERGENCY' THEN Null
WHEN 'NS AM' THEN Null
WHEN 'CATIP' THEN Null
WHEN 'Rescue Tru' THEN Null
WHEN 'MAC T' THEN Null
WHEN 'ABULA' THEN 'Ambulance'
WHEN 'H3' THEN Null
WHEN 'DEPARTMENT' THEN Null
WHEN 'SCHOOL  BU' THEN 'Schoolbus'
WHEN 'Ford picku' THEN 'Pickup Truck'
WHEN 'icecr' THEN 'Ice Cream Truck'
WHEN 'Sweeper' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'ESCOOTER S' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'FREIGHT FL' THEN Null
WHEN 'NY CITY MT' THEN Null
WHEN 'FEDEX TRUC' THEN 'Small Cargo Vehicles'
WHEN 'FLAT-' THEN Null
WHEN 'BKHOE' THEN 'Construction'
WHEN 'Combinatio' THEN Null
WHEN 'SPR' THEN Null
WHEN 'ALL TERRAI' THEN Null
WHEN 'SELF-INSUR' THEN Null
WHEN 'HORSE DRAW' THEN 'Horse'
WHEN 'TRANSPORTE' THEN Null
WHEN 'MINIVAN' THEN 'Van'
WHEN 'NYC PARKS' THEN Null
WHEN '18 WH' THEN 'Large Cargo Vehicles'
WHEN 'PU' THEN Null
WHEN 'NT TR' THEN Null
WHEN 'CONVE' THEN Null
WHEN 'gokar' THEN Null
WHEN 'TOWMA' THEN Null
WHEN 'moped scoo' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'Backhoe Lo' THEN 'Construction'
WHEN 'east' THEN Null
WHEN 'VOLVO' THEN Null
WHEN 'Trolley ri' THEN Null
WHEN 'YELLOW TAX' THEN 'Taxi'
WHEN 'wag' THEN Null
WHEN 'TOW-TRUCK' THEN 'Tow Trucks'
WHEN 'TRUCK/VAN' THEN 'Van'
WHEN 'FRONT LOAD' THEN Null
WHEN 'CAT FORKLI' THEN 'Construction'
WHEN 'GOV V' THEN Null
WHEN 'USPS #6530' THEN 'USPS'
WHEN 'UTILITY WH' THEN Null
WHEN 'MINI SCHOO' THEN 'Schoolbus'
WHEN 'FIRET TRUC' THEN 'Fire Department Vehicles'
WHEN 'TRANSPORT' THEN Null
WHEN 'GOVENMENT' THEN Null
WHEN 'commerial' THEN 'Unidentified Commercial Vehicles'
WHEN 'electronic' THEN Null
WHEN 'Govt P/U T' THEN Null
WHEN 'JETSKI' THEN Null
WHEN 'YELLOWPOWE' THEN Null
WHEN '2- to' THEN Null
WHEN 'e skate bo' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN '197209' THEN Null
WHEN '4SEDN' THEN 'Sedan'
WHEN 'CAT' THEN 'Construction'
WHEN 'Pickup tow' THEN 'Tow Trucks'
WHEN 'F150XL PIC' THEN Null
WHEN 'e-350' THEN Null
WHEN 'REVEL' THEN Null
WHEN 'EMRGN' THEN Null
WHEN 'Snowmobile' THEN Null
WHEN 'FLATBED FR' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'SKID-' THEN Null
WHEN 'mtr s' THEN Null
WHEN 'POIS' THEN Null
WHEN 'T/ CR' THEN Null
WHEN 'bsd' THEN Null
WHEN 'BOOM MOPED' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'FDNY Vehic' THEN 'Fire Department Vehicles'
WHEN 'PV HOLDING' THEN Null
WHEN 'White Van' THEN 'Van'
WHEN '99999' THEN Null
WHEN 'VAB' THEN Null
WHEN 'Commer Veh' THEN 'Unidentified Commercial Vehicles'
WHEN 'COMM TRAIL' THEN Null
WHEN 'Landscapin' THEN Null
WHEN 'USPS/GOVT' THEN 'USPS'
WHEN 'CATAPILLAR' THEN 'Construction'
WHEN 'HOSRE' THEN 'Horse'
WHEN 'PUSH SCOOT' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'UNKNW' THEN Null
WHEN 'ONE WHEEL' THEN Null
WHEN 'AMABU' THEN Null
WHEN 'santa' THEN Null
WHEN 'Dumb Truck' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'ESU REP' THEN Null
WHEN 'CITYWIDE' THEN Null
WHEN '7532433' THEN Null
WHEN 'NYC MTA BU' THEN Null
WHEN 'In Line Sk' THEN Null
WHEN 'Nova' THEN Null
WHEN 'MOT' THEN Null
WHEN 'NTTRL' THEN Null
WHEN 'sgws' THEN Null
WHEN 'LADDER 34' THEN Null
WHEN 'LIBER' THEN Null
WHEN 'Station Wa' THEN Null
WHEN 'A-ONE' THEN Null
WHEN 'TRUCK VAN' THEN Null
WHEN 'cm' THEN Null
WHEN 'WHIT' THEN Null
WHEN 'MAIL CARRI' THEN Null
WHEN 'LIABITIY' THEN Null
WHEN 'BROOM' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN '2 TON' THEN Null
WHEN 'Unmarked V' THEN Null
WHEN 'HWH' THEN Null
WHEN 'SPECIAL CO' THEN Null
WHEN 'nat grid t' THEN Null
WHEN 'MOTORHOME' THEN 'Motor Home'
WHEN 'GEN  AMBUL' THEN 'Ambulance'
WHEN 'FREE' THEN Null
WHEN 'GOVT.' THEN Null
WHEN 'PROGRESSIV' THEN Null
WHEN 'LD' THEN Null
WHEN 'MAXIM' THEN Null
WHEN '2 wheel sc' THEN Null
WHEN 'Sprinter W' THEN 'Small Cargo Vehicles'
WHEN 'SC' THEN Null
WHEN '4 axe' THEN 'Large Cargo Vehicles'
WHEN 'KME/F' THEN Null
WHEN 'FIRER' THEN Null
WHEN 'Fdny Ems T' THEN 'Fire Department Vehicles'
WHEN 'TRUCK CRAN' THEN Null
WHEN 'f15' THEN Null
WHEN 'REVEL MOPE' THEN Null
WHEN 'FDNY INSUR' THEN 'Fire Department Vehicles'
WHEN 'Van (' THEN Null
WHEN 'Barri' THEN Null
WHEN 'none' THEN Null
WHEN 'ROOD' THEN Null
WHEN 'NYS A' THEN Null
WHEN 'te' THEN Null
WHEN 'FDNY- Fire' THEN 'Fire Department Vehicles'
WHEN 'TRAILER CA' THEN Null
WHEN 'NIU' THEN Null
WHEN 'City vehic' THEN Null
WHEN 'DEPT VAN #' THEN Null
WHEN 'MARK' THEN Null
WHEN 'hi-lo' THEN Null
WHEN 'yellow cab' THEN Null
WHEN 'nyu s' THEN Null
WHEN 'SKID STEER' THEN Null
WHEN 'Car carrie' THEN Null
WHEN 'LOCOMOTIVE' THEN Null
WHEN 'ENGINE SP0' THEN Null
WHEN 'escavator' THEN Null
WHEN 'CABIN' THEN Null
WHEN 'Token' THEN Null
WHEN '999' THEN Null
WHEN 'Asphalt Pa' THEN Null
WHEN 'SW/VAN' THEN Null
WHEN 'FDNY LADER' THEN 'Fire Department Vehicles'
WHEN 'LIT DIRECT' THEN Null
WHEN 'DOT R' THEN Null
WHEN 'Tram' THEN Null
WHEN 'subar' THEN Null
WHEN 'YW PO' THEN Null
WHEN '?omme' THEN Null
WHEN 'METRO TRAN' THEN Null
WHEN 'T880' THEN Null
WHEN 'ems b' THEN Null
WHEN 'Lim' THEN Null
WHEN 'MOBILITY S' THEN Null
WHEN 'forlift' THEN 'Construction'
WHEN 'CAT.' THEN Null
WHEN 'DELV WH' THEN Null
WHEN 'City Bus' THEN 'Bus'
WHEN 'camper tra' THEN Null
WHEN 'I-haul' THEN Null
WHEN 'E450' THEN Null
WHEN 'LCOM' THEN Null
WHEN '4' THEN Null
WHEN 'NYPD VAN' THEN Null
WHEN 'Piggy back' THEN Null
WHEN 'SHUTTLE BU' THEN 'Bus'
WHEN 'Lawnmower' THEN Null
WHEN 'kick scoot' THEN Null
WHEN 'FUSION' THEN Null
WHEN 'SWEEPER TR' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'TR/KI' THEN Null
WHEN 'MARKED RMP' THEN Null
WHEN 'Nissan' THEN Null
WHEN 'STACK' THEN Null
WHEN 'PSP' THEN Null
WHEN 'box van' THEN Null
WHEN 'CAR/SUV' THEN Null
WHEN '11-VA' THEN Null
WHEN 'BOX CAR' THEN Null
WHEN 'HUMVEE' THEN Null
WHEN 'ASPHALT RO' THEN Null
WHEN '1C' THEN Null
WHEN 'LIEBH' THEN Null
WHEN 'TRUCK COMM' THEN Null
WHEN 'Tow-t' THEN Null
WHEN 'SYBN' THEN Null
WHEN 'R/V C' THEN Null
WHEN '12 passage' THEN Null
WHEN 'E3' THEN Null
WHEN 'GAS POWERE' THEN Null
WHEN 'AMUBULANCE' THEN 'Ambulance'
WHEN 'POLIC' THEN 'Police'
WHEN 'LOADE' THEN Null
WHEN '2 DR' THEN Null
WHEN 'Collection' THEN Null
WHEN 'PROMASTER' THEN Null
WHEN 'FIRTRUCK' THEN 'Fire Department Vehicles'
WHEN 'USPS2' THEN 'USPS'
WHEN 'UTLIT' THEN Null
WHEN 'U-Haul min' THEN 'Box Truck'
WHEN 'MVP' THEN Null
WHEN 'SCOMM' THEN Null
WHEN 'U HAUL TRU' THEN 'Box Truck'
WHEN 'CHART' THEN Null
WHEN 'FDNY mecha' THEN 'Fire Department Vehicles'
WHEN 'MILITARY' THEN Null
WHEN 'CARRIER' THEN Null
WHEN 'MANUAL SCO' THEN Null
WHEN 'D2' THEN Null
WHEN 'sanitaion' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'TKTR' THEN Null
WHEN 'passa' THEN Null
WHEN 'omni' THEN 'Bus'
WHEN 'depar' THEN Null
WHEN 'LMTV' THEN Null
WHEN 'COM T' THEN Null
WHEN '10 Paaseng' THEN 'Bus'
WHEN 'RIV 2022' THEN Null
WHEN 'RINGO' THEN Null
WHEN 'Isuzu' THEN Null
WHEN 'M2' THEN Null
WHEN 'COMER' THEN Null
WHEN 'SD' THEN Null
WHEN 'TRANSIT VA' THEN Null
WHEN 'delviery' THEN Null
WHEN 'SWEPE' THEN Null
WHEN 'PEPSI DELI' THEN 'Small Cargo Vehicles'
WHEN 'PEDAL BIKE' THEN 'Bikes & Self Propelled Vehicles'
WHEN 'BOX H' THEN Null
WHEN 'DOT TRUCK' THEN Null
WHEN 'EMS/VAN' THEN Null
WHEN 'HI TA' THEN Null
WHEN 'NO/BU' THEN Null
WHEN 'HEAVY TRUC' THEN Null
WHEN 'X TRL' THEN Null
WHEN 'FDNY 245 E' THEN 'Fire Department Vehicles'
WHEN 'del truck' THEN Null
WHEN '3DOOR' THEN 'Sedan'
WHEN 'C 1' THEN Null
WHEN 'U-HAUL TRU' THEN 'Box Truck'
WHEN 'RV/VAN' THEN Null
WHEN 'GRUMM' THEN Null
WHEN 'VANG' THEN Null
WHEN 'COMMM' THEN Null
WHEN 'TL TR' THEN Null
WHEN 'COLL' THEN Null
WHEN 'Waste truc' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'Mercedes' THEN Null
WHEN '4whee' THEN Null
WHEN 'R.M.P.' THEN Null
WHEN 'BOAT' THEN 'Boat'
WHEN 'MAC' THEN Null
WHEN 'MDX' THEN Null
WHEN 'Stake' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'gas mo ped' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'usps  van' THEN 'USPS'
WHEN 'H1' THEN Null
WHEN 'E REVEL SC' THEN Null
WHEN 'BTM' THEN Null
WHEN 'FORK-' THEN Null
WHEN 'Traffic To' THEN Null
WHEN 'seagr' THEN Null
WHEN '315 e' THEN Null
WHEN '4 RUN' THEN Null
WHEN 'TRAC.' THEN Null
WHEN 'Fd fi' THEN Null
WHEN 'Yellow sch' THEN Null
WHEN 'Dent and S' THEN Null
WHEN 'TRAILER/FL' THEN Null
WHEN 'U.S. POSTA' THEN 'USPS'
WHEN 'US MA' THEN Null
WHEN 'ELEC. UNIC' THEN Null
WHEN 'TRLR PLT,' THEN Null
WHEN 'g scl' THEN Null
WHEN 'FRHT TRAIL' THEN Null
WHEN 'BACK HOE' THEN Null
WHEN 'BLOCK' THEN Null
WHEN 'TRUCK FLAT' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN '11111' THEN Null
WHEN 'MOTORIZEDS' THEN Null
WHEN 'VAGON' THEN Null
WHEN 'Ford EC2' THEN Null
WHEN 'OLC' THEN Null
WHEN 'COACH' THEN Null
WHEN 'frh' THEN Null
WHEN 'E-SKATEBOA' THEN Null
WHEN 'Pick wh' THEN Null
WHEN 'dhl t' THEN Null
WHEN 'COUPE' THEN 'Sedan'
WHEN 'CHEVR' THEN Null
WHEN 'RV/Tr' THEN Null
WHEN 'G Sem' THEN Null
WHEN 'REN' THEN Null
WHEN 'MOPED 150C' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'com v' THEN Null
WHEN 'TRUCK W/TR' THEN Null
WHEN 'POSTAL VEH' THEN 'USPS'
WHEN 'omm' THEN Null
WHEN 'CHERV' THEN Null
WHEN 'HD' THEN Null
WHEN 'MOOPER' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'prks' THEN Null
WHEN 'BOXTRUCK' THEN 'Box Truck'
WHEN 'ARMOR' THEN 'Armored Truck'
WHEN 'NYFD ambul' THEN 'Fire Department Vehicles'
WHEN 'Pas (4dr s' THEN Null
WHEN 'ECOM' THEN Null
WHEN 'SEDONA' THEN Null
WHEN 'FD LADDER' THEN 'Fire Department Vehicles'
WHEN '35 FT' THEN Null
WHEN 'ME/BE' THEN Null
WHEN 'US GO' THEN Null
WHEN 'Ladder' THEN Null
WHEN 'G1' THEN Null
WHEN 'nyfd' THEN 'Fire Department Vehicles'
WHEN 'g spc' THEN Null
WHEN 'Thomas' THEN Null
WHEN 'Go kart' THEN Null
WHEN 'range' THEN Null
WHEN 'U-HAL' THEN 'Box Truck'
WHEN '5' THEN Null
WHEN 'UNKWOWN' THEN Null
WHEN 'G1`' THEN Null
WHEN 'fedx' THEN 'Small Cargo Vehicles'
WHEN 'E- Bi' THEN Null
WHEN 'SEA' THEN Null
WHEN 'APORT' THEN Null
WHEN 'PSR' THEN Null
WHEN 'EMS -BUS' THEN Null
WHEN 'GMC ECOM' THEN Null
WHEN 'RMP V' THEN Null
WHEN 'US MAIL #1' THEN 'USPS'
WHEN 'EC3' THEN Null
WHEN 'sanitaton' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'ManPower s' THEN Null
WHEN 'KUBOT' THEN Null
WHEN 'STREET' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'LTRL' THEN Null
WHEN 'SERVI' THEN Null
WHEN 'TRANSIT' THEN 'Construction'
WHEN 'bobct' THEN 'Construction'
WHEN 'PASS VAN' THEN 'Van'
WHEN 'MTA V' THEN Null
WHEN 'C0MME' THEN Null
WHEN 'SANMEN COU' THEN Null
WHEN 'UHAL' THEN 'Box Truck'
WHEN 'Penske Box' THEN 'Box Truck'
WHEN 'E MOTORCYC' THEN Null
WHEN 'f1' THEN Null
WHEN 'SPARK150 S' THEN Null
WHEN 'Ford FF' THEN Null
WHEN 'Ford f150' THEN Null
WHEN 'FORD F-150' THEN Null
WHEN 'ATTECHMENT' THEN Null
WHEN 'GARBAGE ST' THEN Null
WHEN 'NYC BUS' THEN Null
WHEN 'John' THEN Null
WHEN 'VANET' THEN Null
WHEN 'EMI- TRAIL' THEN Null
WHEN 'Food Trail' THEN Null
WHEN 'E Bike w p' THEN Null
WHEN 'Utility.' THEN Null
WHEN 'tr/tr' THEN Null
WHEN '26 ft' THEN Null
WHEN 'E-UNICYCLE' THEN Null
WHEN 'Pro master' THEN Null
WHEN 'Bread truc' THEN Null
WHEN 'CMS-T' THEN Null
WHEN 'ELEC.' THEN Null
WHEN 'CAMPER VAN' THEN Null
WHEN '3DC-' THEN Null
WHEN 'Limousine' THEN Null
WHEN 'SUDN' THEN Null
WHEN 'utv bobcat' THEN Null
WHEN 'SLINGSHOT' THEN Null
WHEN 'towe truck' THEN Null
WHEN 'SCL' THEN Null
WHEN 'cross' THEN Null
WHEN 'GE/SC' THEN Null
WHEN 'PASS-' THEN Null
WHEN '.' THEN Null
WHEN 'UNK BOX TR' THEN Null
WHEN 'FD TRUCK' THEN Null
WHEN 'J1' THEN Null
WHEN 'f-250' THEN Null
WHEN '0' THEN Null
WHEN 'FDNY CHIEF' THEN Null
WHEN 'TR-Trailer' THEN Null
WHEN 'Mecha' THEN Null
WHEN 'small' THEN Null
WHEN 'FLED' THEN Null
WHEN 'PUMPE' THEN Null
WHEN '9999' THEN Null
WHEN 'MTR H' THEN Null
WHEN 'Yamaha' THEN Null
WHEN 'TIR' THEN Null
WHEN 'DEMA-' THEN Null
WHEN 'A,n' THEN Null
WHEN 'COMMERICIA' THEN Null
WHEN 'NYPD Traff' THEN Null
WHEN 'scooc' THEN Null
WHEN 'UHUAL' THEN Null
WHEN 'POSTO' THEN Null
WHEN 'KP160' THEN Null
WHEN 'CONTR' THEN Null
WHEN 'REVEL scoo' THEN Null
WHEN 'moter' THEN Null
WHEN 'MOVING TRU' THEN Null
WHEN 'USPS TRUC,' THEN Null
WHEN 'e tow' THEN Null
WHEN 'FORD AMBUL' THEN Null
WHEN 'Flat bed t' THEN Null
WHEN 'MINI VAHN' THEN Null
WHEN '7' THEN Null
WHEN 'G AMB' THEN Null
WHEN 'USP M' THEN Null
WHEN 'School van' THEN Null
WHEN 'NYC M' THEN Null
WHEN 'CHASSIS &' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'e bike uni' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'VAN/B' THEN 'Van'
WHEN 'LSA' THEN Null
WHEN 'Kubota bac' THEN Null
WHEN 'VERZION VA' THEN Null
WHEN 'Ram Promas' THEN Null
WHEN 'UNKN' THEN Null
WHEN 'NYC a' THEN Null
WHEN 'conta' THEN Null
WHEN 'Grail' THEN Null
WHEN 'Dept Tow t' THEN 'Tow Trucks'
WHEN 'SEMI TRUCK' THEN 'Large Cargo Vehicles'
WHEN 'TAN P' THEN Null
WHEN 'YALE' THEN Null
WHEN 'UPS M' THEN 'Small Cargo Vehicles'
WHEN 'POLICE VEH' THEN 'Police'
WHEN 'charter bu' THEN Null
WHEN '''lime mope' THEN Null
WHEN 'TTAILER' THEN 'Trailers'
WHEN 'GOLF CAR' THEN 'Carryall, Golf Carts & Similar'
WHEN 'crane boom' THEN 'Construction'
WHEN 'WORKH' THEN Null
WHEN 'Farm Vehicle' THEN 'Agriculture'
WHEN 'push' THEN Null
WHEN 'Comix' THEN Null
WHEN 'Yamah' THEN Null
WHEN '250-3' THEN Null
WHEN 'CUSHM' THEN Null
WHEN 'ukn' THEN Null
WHEN 'YELLOW BUS' THEN 'Bus'
WHEN 'Usaa' THEN Null
WHEN 'SMYELLSCHO' THEN Null
WHEN 'FDNY EMS#1' THEN Null
WHEN 'atv p' THEN Null
WHEN 'ELECTRIC C' THEN Null
WHEN 'principle' THEN Null
WHEN 'SMART CAR' THEN Null
WHEN 'TRACK EXCA' THEN Null
WHEN 'Lift' THEN Null
WHEN 'USPS # 487' THEN 'USPS'
WHEN 'Gas dirt b' THEN Null
WHEN 'COT' THEN Null
WHEN 'CMIXER' THEN Null
WHEN 'BED T' THEN Null
WHEN 'ELECTRIC B' THEN Null
WHEN 'Wh Ford co' THEN Null
WHEN 'Carriage' THEN Null
WHEN 'GOVERMENT' THEN Null
WHEN 'UTILITY VA' THEN Null
WHEN 'ulili' THEN Null
WHEN 'PS' THEN Null
WHEN 'UPS' THEN 'Small Cargo Vehicles'
WHEN 'TRAILOR' THEN 'Trailers'
WHEN 'RGR' THEN Null
WHEN 'CRF Carria' THEN Null
WHEN 'van c' THEN Null
WHEN 'CHERR' THEN Null
WHEN 'USPCS' THEN 'USPS'
WHEN '2015' THEN Null
WHEN 'P/SE' THEN Null
WHEN 'semi-trail' THEN Null
WHEN 'Postoffice' THEN 'USPS'
WHEN 'TLR' THEN Null
WHEN 'SANTI' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'COMB' THEN Null
WHEN 'DUMPTRUCK' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'ORION' THEN Null
WHEN 'Flatbed Pi' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'SFI' THEN Null
WHEN 'yy' THEN Null
WHEN 'Small Bus' THEN 'Bus'
WHEN 'DELV BR' THEN Null
WHEN 'almbulance' THEN 'Ambulance'
WHEN 'E ONE' THEN Null
WHEN 'BLACK' THEN Null
WHEN 'Ford Couri' THEN Null
WHEN 'BUS (OMNIB' THEN 'Bus'
WHEN 'LSV' THEN Null
WHEN '985' THEN Null
WHEN 'DEIV' THEN Null
WHEN 'Toyota' THEN Null
WHEN 'PET' THEN Null
WHEN 'VAN E' THEN Null
WHEN 'Pvt Ambula' THEN Null
WHEN 'HERTZ RAM' THEN Null
WHEN 'DOT EQUIPM' THEN Null
WHEN 'rz' THEN Null
WHEN 'Front-Load' THEN Null
WHEN 'postal bus' THEN 'USPS'
WHEN 'DELVI' THEN Null
WHEN 'DOT T' THEN Null
WHEN 'Snow' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'Stand up s' THEN Null
WHEN 'Military v' THEN Null
WHEN 'HD To' THEN Null
WHEN 'FREIGT VAN' THEN Null
WHEN 'GOVT' THEN Null
WHEN 'MTA truck' THEN Null
WHEN 'PRIVA' THEN Null
WHEN 'TC' THEN Null
WHEN 'F650' THEN Null
WHEN 'FR`' THEN Null
WHEN 'OML/OMNIBU' THEN Null
WHEN 'OZ MO' THEN Null
WHEN 'SM YW' THEN Null
WHEN 'AMBULANVE' THEN 'Ambulance'
WHEN 'MTA Van' THEN 'Van'
WHEN 'FRT' THEN Null
WHEN '12 PASSENG' THEN Null
WHEN 'FLYWING MO' THEN Null
WHEN 'delie' THEN 'Delivery'
WHEN 'AMBALANCE' THEN 'Ambulance'
WHEN 'USPS small' THEN 'USPS'
WHEN 'MTA U' THEN Null
WHEN 'AERIA' THEN Null
WHEN 'REG' THEN Null
WHEN 'CHEVY EXPR' THEN Null
WHEN '997' THEN Null
WHEN 'CAB' THEN Null
WHEN 'SUBN/Van' THEN Null
WHEN 'Mo pa' THEN Null
WHEN 'OMT/T' THEN Null
WHEN 'police rep' THEN 'Police'
WHEN 'FedEx box' THEN Null
WHEN 'SKID LOADE' THEN Null
WHEN 'MARKED VAN' THEN Null
WHEN 'LCOMM' THEN Null
WHEN 'D/V WB' THEN Null
WHEN 'rmb' THEN Null
WHEN 'usps 88716' THEN 'USPS'
WHEN 'FDNY EMT' THEN 'Fire Department Vehicles'
WHEN 'FREIG DELV' THEN 'Large Cargo Vehicles'
WHEN 'dilevery t' THEN 'Delivery'
WHEN 'NYC FD' THEN 'Fire Department Vehicles'
WHEN 'COMMU' THEN Null
WHEN 'cp' THEN Null
WHEN 'US Mail Tr' THEN 'USPS'
WHEN 'FLAT  BED' THEN 'Small Commercial Trucks - Flatbed & Chassis Cab'
WHEN 'backhoe re' THEN 'Construction'
WHEN 'Feder' THEN Null
WHEN 'PAS V' THEN Null
WHEN 'progr' THEN Null
WHEN 'Unknown ve' THEN Null
WHEN 'COM DELIVE' THEN Null
WHEN 'del' THEN Null
WHEN 'NJ transit' THEN Null
WHEN 'refuse tru' THEN Null
WHEN 'pay loader' THEN Null
WHEN 'conti' THEN Null
WHEN 'VAN WH' THEN Null
WHEN 'TCM' THEN Null
WHEN 'Garbage' THEN 'Sanitation, Sweep & Public Utility Vehicles'
WHEN 'FDNY #226' THEN 'Fire Department Vehicles'
WHEN 'CONT' THEN Null
WHEN 'TAILG' THEN Null
WHEN 'UNKOWN' THEN Null
WHEN 'CON E' THEN Null
WHEN 'SAVANA' THEN Null
WHEN 'HIGHL' THEN Null
WHEN 'P/U' THEN Null
WHEN '2 WHE' THEN Null
WHEN 'TLC P' THEN Null
WHEN 'CAMP' THEN Null
WHEN 'high' THEN Null
WHEN 'BULLDOZER' THEN 'Construction'
WHEN 'message si' THEN Null
WHEN 'White ambu' THEN 'Ambulance'
WHEN 'ROADS' THEN Null
WHEN 'dark color' THEN Null
WHEN 'WORKM' THEN Null
WHEN '2000' THEN Null
WHEN '100th truc' THEN Null
WHEN 'Truck/bus' THEN Null
WHEN 'WINEB' THEN Null
WHEN 'CHEVROLET' THEN Null
WHEN 'MO PE' THEN 'Mopeds, Motorized Scooters & Similar'
WHEN 'SURET' THEN Null
WHEN '50cc mini' THEN Null
WHEN 'Ele. Unicy' THEN Null
WHEN 'Parce' THEN Null
WHEN 'MCY B' THEN Null
WHEN 'HDC' THEN Null
WHEN 'DOT VEHICL' THEN Null
WHEN 'FDNY UTILI' THEN 'Fire Department Vehicles'
WHEN '13' THEN Null
ELSE 'Undefined'
END

--Overwrite the faulty vehicle codes in the original database with the new ones in TempTable, via a Join on CollisionID
UPDATE Target
SET Target.[VEHICLE_TYPE_CODE_1] = OG.[VEHICLE_TYPE_CODE_1]
FROM [NYC_Collisions].[dbo].[Motor_Vehicle_Collisions_-_Crashes] Target
JOIN tempdb.dbo.##TempTable OG
ON Target.[COLLISION_ID] = OG.[COLLISION_ID];

--Drop the TempTable
DROP TABLE ##TempTable